### ISSUE TITLE
Spec compliance: Int vs Int32

### ISSUE THREAD

**Issue by msvbg** [morpheusgraphql/morpheus-graphql#117]
This may be a little bit picky, but [the spec says](https://graphql.github.io/graphql-spec/draft/#sec-Int) that Ints are 32-bit integers. Haskell's `Int` type, used here, is [at least a signed 30-bit integer](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Int.html#t:Int), probably due to [tagged pointer representation](https://stackoverflow.com/a/3774467/2144792). (Although on my system it's a 64-bit int, and I suppose this is quite common).

For full spec compliance, the API could be changed to use `Int32` from `Data.Int` everywhere. This might make things a little bit uglier because you would have to use `Int32` everywhere, and I'm not sure about GHC implementation details but maybe `Int32` is boxed on 32-bit platforms due to not being able to use the 30-bit optimization trick. Or it could be argued that this is not worth the trouble.

**Comment by msvbg** [comment]
Similarly, [floats](https://graphql.github.io/graphql-spec/June2018/#sec-Float) are supposed to be double precision floats.

**Comment by nalchevanidze** [comment]
Hi. thank you for contributing! I sent invitation to you for this project

it seems not so terrible to replace it with `Int32`, but I will propose that we wait, anyway it is not so hard to implement.

**Comment by nalchevanidze** [comment]
for about 4 years there are no more reactions about it, I think I can close.
