### ISSUE TITLE
Other communication than just issues

### ISSUE THREAD

**Issue by msvbg** [morpheusgraphql/morpheus-graphql#119]
It would be nice if there was some kind of channel like Spectrum/Discord/Slack/IRC where you can discuss/ask questions without opening an issue.

**Comment by nalchevanidze** [comment]
Slack? i made slack channel for it "morpheus-graphql"

**Comment by nalchevanidze** [comment]
you can send me your emal on "d.nalchevanidze@gmail.com" and i will send you invitation

**Comment by msvbg** [comment]
martin@martinsvanberg.com
