### ISSUE TITLE
Feature/Enhance Server with custom InputUnion Validation

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#174]
## support Input Union

Enhance GraphQL server so that it recognises input object,  but does not break client Libraries 

```haskell

data Cat = Cat { catName :: Text }  

data Dog = Dog { dogName :: Text } 

type instance Kind Pet = INPUT_UNION

data Pet = CAT Cat | DOG Dog deriving (Generic, GQLType) 
```
or Just 

```haskell
type instance Kind Pet = INPUT_UNION

data Pet = Cat { catName :: Text }  | Dog { dogName :: Text } deriving (Generic, GQLType)
```
union types like `Pet` , can be automatically derived as GraphQL `enum` for possible type names and `input` that contains actual types as fields

```gql 
enum PetTags { 
  Cat
  Dog
}

input Pet {
    typeTag: PetTags!
    typeCat: Cat
    typeDog: Dog
}
```

so server decodes input:

```json
{ 
  "__typename": "Dog",
  "Dog" : {
     "dogName" : "Milo"
   }
} 
```
to 
```haskell
Dog { dogName = "Milo" }
```

and input:

```json
{ 
  "typeTag": "Cat",
  "typeDog" : {
     "dogName" : "Milo"
   }
} 
```
will throw Validation Error

so we don't break client libraries because we use `Standart` GraphQL types and validate them differently in Server. and we don't modify `GraphQL` Schema

**Comment by horus** [comment]
Besides that, I wonder if we could have custom names for each of these fields:
```haskell
data DogType = Barky | Mildy | Eatty
data Dog = { dogName :: Text, typ :: DogType } -- avoid the "type" keyword
```
The example above would require something named `typ` when used as input argument.
Maybe it's better to give everyone a chance to override?

**Comment by nalchevanidze** [comment]
@horus i don't get what do you mean?  can you explain it with an concrete Example? 

and thank you for your contributing.

**Comment by horus** [comment]
Sorry I didn't make it more clear.

Simply put, in my example, I want to freely decide the actually parameter name of the field, i.e., I might call it `type` instead of `typ`. But in current implementation, the name of the parameter, if I read it correctly, is derived from its definition, resulting in an unchangeable one.

Compare to other implementation (haskell-graphql/graphql-api in question):
```haskell
type Hello = Object "Hello" '[]
  '[ Argument "who" Text :> Field "greeting" Text ]
```

...here you can name the argument `who`, even `type`. It won't be conflict with the language keyword `type`.

Anyways, I'm not judging which one is superior, just bike-shedding. :-)

**Comment by nalchevanidze** [comment]
hi, i got now, but it is wrong topic for it. we could open pull request for it.

 at the time only reserved name `type` is converted to `type'` so we can extend it and support all reserved names. there are  `convertToJSONName` and `convertToHaskellName` [functions](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Types/Internal/Value.hs#L20) responsible for it.

**Comment by nalchevanidze** [comment]
i opened issue for it #207
