### ISSUE TITLE
Validation/Check duplicate variables on request Body

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#175]
with new release now is possible to validate variable name collision on Query body

https://github.com/bos/aeson/commit/cd4ce0454b842205238c718c93bd2b0ebb7a62a8

**Comment by gvolpe** [comment]
Hi @nalchevanidze , any pointers on where I should start looking if I wanted to get this done?

**Comment by nalchevanidze** [comment]
https://github.com/morpheusgraphql/morpheus-graphql/blob/213512236069aad4c987a619a751516f6e98227e/src/Data/Morpheus/Resolve/Resolve.hs#L60

hier i decode request

**Comment by gvolpe** [comment]
Gotcha! Will try to give it a shot :+1:
