### ISSUE TITLE
Adding a dedicated kind for Type Kinds in Data.Morpheus.Kind?

### ISSUE THREAD

**Issue by ryota-ka** [morpheusgraphql/morpheus-graphql#197]
Currently, `SCALAR`,  `OBJECT` and, so forth, is defined in `Data.Morpheus.Kind` module, and they all have the kind of `*`.
https://github.com/morpheusgraphql/morpheus-graphql/blob/213512236069aad4c987a619a751516f6e98227e/src/Data/Morpheus/Kind.hs#L16-L34

As their kind is `*`, `KIND` type family accepts any `*`-kinded types such as `Bool` or `Int`, which is unexpected and undesirable.
And this will emit an unfriendly error message:

```
    • No instance for (morpheus-graphql-0.1.1:Data.Morpheus.Resolve.Introspect.Introspect
                         Deity
                         Bool
                         morpheus-graphql-0.1.1:Data.Morpheus.Types.Internal.Data.DataArguments)
        arising from a use of ‘interpreter’
    • In the expression: interpreter rootResolver
      In an equation for ‘mythologyApi’:
          mythologyApi = interpreter rootResolver
   |
38 | mythologyApi = interpreter rootResolver
   |                ^^^^^^^^^^^^^^^^^^^^^^^^
```

Instead of defining empty data types separately, we can define them with `DataKinds` extension. In this way the types will have the type of `GQL_KIND`, not `*`.

```haskell
module Data.Morpheus.Kind
  ( SCALAR
  , OBJECT
  , ENUM
  , WRAPPER
  , UNION
  , INPUT_OBJECT
  , INPUT_UNION
  , GQL_KIND -- newly exported
  )
where

-- I wish I had type data...
-- https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0032-type-data.rst
data GQL_KIND
  = SCALAR
  | OBJECT
  | ENUM
  | INPUT_OBJECT
  | UNION
  | INPUT_UNION
  | WRAPPER

type SCALAR = 'SCALAR
type OBJECT = 'OBJECT
type ENUM = 'ENUM
type INPUT_OBJECT = 'INPUT_OBJECT
type UNION = 'UNION
type INPUT_UNION = 'INPUT_UNION
type WRAPPER = 'WRAPPER
```

We'll also need the following changes additionally. (needs `DataKinds`)

```diff
 class GQLType a where
-  type KIND a :: *
+  type KIND a :: GQL_KIND
```

```diff
-class Decode a b where
+class Decode a (b :: GQL_KIND) where
```

```diff
-newtype WithGQLKind a b = WithGQLKind
+newtype WithGQLKind a (b :: GQL_KIND) = WithGQLKind
```

Then, we'll get a relatively straightforward error message, on mistakenly passing `Bool` as an argument to the `KIND` type family.

```
    • Expected kind ‘Data.Morpheus.Kind.GQL_KIND’,
        but ‘Bool’ has kind ‘*’
    • In the type ‘Bool’
      In the type instance declaration for ‘KIND’
      In the instance declaration for ‘GQLType Deity’
   |
24 |   type KIND Deity = Bool
   |                     ^^^^
```

If I'm misunderstanding something, please let me know.
(Especially, you may want to keep `KIND` open-ended.)

Thanks!

**Comment by nalchevanidze** [comment]
thank you. great idea. current error messages  is pain for me too

**Comment by ryota-ka** [comment]
Okay, then I can send a pull request.

btw, do you have any good idea on the name for `GQL_KIND`? I'm not sure it's the best name.
I've noticed it's very similar to [what is called "Type Kinds" in the GraphQL spec](https://graphql.github.io/graphql-spec/draft/#sec-Type-Kinds), but not exactly the same.

**Comment by nalchevanidze** [comment]
i think `GQL_KIND` sound good, it has not exactly same structure as [TypeKind](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Schema/TypeKind.hs)

**Comment by ryota-ka** [comment]
I've sent a pull request! (#204)

**Comment by nalchevanidze** [comment]
i approved it. thank you :)
