### ISSUE TITLE
Feature/ Support GraphQL interfaces in GraphQL document

### ISSUE THREAD

**Issue by charlescrain** [morpheusgraphql/morpheus-graphql#219]
```haskell
defineByDocumentFile
  "./assets/simple.gql"
  [gql|
    query SomeQuery($arg1: String!) {
    ...
    } 
  |]
```

```gql
# simple.gql
interface Node {
  nodeId: ID!
}
type SimpleInterfaceType implements Node {
  nodeId: ID!
  name: String!
}
```

`Interface` and `implements` are treated as unknown keywords while parsing.

@nalchevanidze mentioned building tuples of `(interfaceName, ...interfaceFields)` that can be checked against during validation.

**Comment by nalchevanidze** [comment]
no. i think the best solution is to support interfaces only for schema Validation. 

we will have raw and valid `GQLSchema` , 
 -  `RawSchema`: that will include interfaces too. and will be validated before Morpheus interpreter consumes it.
 - `ValidSchema`: only validated Types. interfaces are excluded (there is no need  to represent them in Haskell, they will be used only for Validation). 

  after validation every: 

  ```
     type SimpleInterfaceType implements Node {
        nodeId: ID!
        name: String!
   }
  ```

  will be converted to just  object type

  ```
     type Node {
        nodeId: ID!
        name: String!
   }
  ```
