### ISSUE TITLE
GraphQL Client: Namespace Client Types and Fields

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#245]
# Problems:

## 1. Type name collision:

 Problems on  Recursive types and alias selections

  For example If we have:

```gql

type Person (id: ID) {
   name: String!
   parent: Person!
   friend: Person!
}

```
And we select 

```gql

{ 
 user {
   name
    friend { 
      name
    }
    parent {
      name
    }
    bestFriend: friend {
      name
      parent {
        name
      }
    }
  }
}
```
We have to Generate 5 Person types with diferent subsets of field, how we name them?

# Solution:

- `User` from `{user`
- `UserFriend`: from `{user{freind`
- `UserParent`: from `{user{parent`
- `UserBestFriend`: from `{user{bestFrend`
- `UserBestFriendParent`: from `{user{bestFrend{parent`
   
each type will have fields with type namespace

**Comment by nalchevanidze** [comment]
maybe is better way do not namespace fields automaticaly:

```gql
{ 
 user {
   name
    friend { 
      friendName: name
    }
    parent {
      parentName: name
    }
  }
}
```

user can namespace field names via GraphQL `alias`

**Comment by nalchevanidze** [comment]
done

**Comment by paradoja** [comment]
Sorry for writing in a closed comment (didn't want to open a new issue for just a comment), but in this case this solution can be a problem if the client tries to use fragments on somewhat complicated schemas:

```graphql
{
  user {
    ... userFields
    friend {
      ... userFields
    }
    parent {
      ...userFields
    }
  }
}

fragment userFields on Person {
  name
  #.....many others
}
```

**Comment by nalchevanidze** [comment]
thanks @paradoja, i  solved it before with as possible as simple method.

since it already implemented, you could open an enhancement issue for that kind of optimisation.

for example Morheus compiler could check and generate only one type if multiple types have same selection structure.

**Comment by paradoja** [comment]
I have a current project that may bump into this soon (I can actually sidestep it, but I may branch it to have the issue). I'll play a bit with it and then open an issue when I have a better idea on how it would be tackled, although I do like your idea.
