### ISSUE TITLE
fetch sets variables to [] if no arguments are present

### ISSUE THREAD

**Issue by sordina** [morpheusgraphql/morpheus-graphql#272]
Testing Morpheus client against my API it appears that if no arguments are passed to `fetch` then `variables` in the request body is set to `[]` instead of `{}`. This causes issues on some servers.

Tested against: `    hackage: morpheus-graphql-0.4.0@sha256:73420c02c2807c9861d2fc52ed31691cae68a11e40051a1db99071e68507e625,21405`

Let me know if you need additional info for the bug report of if this is out of date!

**Comment by sordina** [comment]
I believe that this is being caused by `()` being accepted as a placeholder for empty arguments:

```
*Main> A.encode ()
"[]"
```

**Comment by sordina** [comment]
Can be seen in `src/Data/Morpheus/Execution/Client/Build.hs`.

Could possibly expose a different unit type that encodes to `{}`.

**Comment by sordina** [comment]
Tested locally and it works.

src/Data/Morpheus/Execution/Client/Build.hs:

```
queryArgumentType :: Maybe TypeD -> (Type, Q [Dec])
queryArgumentType Nothing                       = (ConT $ mkName "NoArgs", pure [])
queryArgumentType (Just rootType@TypeD {tName}) = (ConT $ mkName tName, declareInputType rootType)
```

And at the use site:

```
instance A.ToJSON NoArgs where
    toJSON NoArgs = A.object []
```

Could include in Types?

**Comment by sordina** [comment]
I guess this would be a bad idea though since it might break backwards compatibility. Maybe the best approach is to make a custom instance for `ToJSON` for `GQLRequest`.

**Comment by nalchevanidze** [comment]
thank you for your issue, i will check out it. I think that `()` is correct for no arguments. id don't want to create new type for empty object

**Comment by sordina** [comment]
The spec seems to indicate that enumeration is the only required property of the variables set:

https://graphql.github.io/graphql-spec/June2018/#sec-Coercing-Variable-Values

This means that the issue could actually be a server-side bug, still trying to dig in deeper to confirm.

**Comment by sordina** [comment]
FYI the server implementation that breaks on `[]` is https://github.com/rmosolgo/graphql-ruby

**Comment by sordina** [comment]
On closer inspection of the spec it does seem like variables should be an object:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/92299/66883631-4e00c500-f01a-11e9-940e-afa0e7d60156.png">

**Comment by sordina** [comment]
I think this slightly dodgy workaround or something similar should allow for preservation of backwards compatibility, and meeting spec for empty arguments:

```
± git df
diff --git a/src/Data/Morpheus/Execution/Client/Fetch.hs b/src/Data/Morpheus/Execution/Client/Fetch.hs
index b4e4410..d0fee38 100644
--- a/src/Data/Morpheus/Execution/Client/Fetch.hs
+++ b/src/Data/Morpheus/Execution/Client/Fetch.hs
@@ -16,11 +16,18 @@ import           Data.ByteString.Lazy            (ByteString)
import           Data.Text                       (pack)
import           Language.Haskell.TH

{+import qualified Data.Aeson       as A+}
{+import qualified Data.Aeson.Types as A+}

--
-- MORPHEUS
import           Data.Morpheus.Types.Internal.TH (instanceHeadT)
import           Data.Morpheus.Types.IO          (GQLRequest (..), JSONResponse (..))

{+fixVars :: A.Value -> A.Value+}
{+fixVars x | x == A.emptyArray = A.emptyObject+}
{+fixVars x = x+}

class Fetch a where
  type Args a :: *
  __fetch ::
@@ -32,7 +39,7 @@ class Fetch a where
    -> m (Either String a)
  __fetch strQuery opName trans vars = (eitherDecode >=> processResponse) <$> trans (encode gqlReq)
    where
      gqlReq = GQLRequest {operationName = Just (pack opName), query = pack strQuery, variables = Just {+(fixVars+} (toJSON [-vars)}-]{+vars))}+}
      -------------------------------------------------------------
      processResponse JSONResponse {responseData = Just x} = pure x
      processResponse invalidResponse                      = fail $ show invalidResponse
```

**Comment by nalchevanidze** [comment]
filed 'variables' is optional. i would prefer 
```hs 
fixVars :: A.Value -> Maybe A.Value 
fixVars x 
   | x == A.emptyArray = Nothing
   | otherwise = Just x
```

**Comment by sordina** [comment]
@nalchevanidze ah that's much cleaner!

**Comment by sordina** [comment]
Would you like a PR?

**Comment by nalchevanidze** [comment]
sure, would be great

**Comment by nalchevanidze** [comment]
Solved. thanks to @sordina
