### ISSUE TITLE
Does not parse github v4 graphql schema

### ISSUE THREAD

**Issue by shapr** [morpheusgraphql/morpheus-graphql#275]
I suspect this is a feature request.
I'm using the github library from hackage to hit the github v3 library and would much rather use the github v4 graphql library.

I tried the demo code but replaced `importGQLDocumentWithNamespace "schema.gql"` with a reference to the `schema.graphql` from https://github.com/octokit/graphql-schema and received parse errors.
`    [{"message":"offset=11407:\nunexpected '@'\nexpecting \"\"\"\"\", '!', '#', ',', '}', entry, or white space\n","locations":[{"line":691,"column":14}]}]`

I looked at that line ( https://github.com/octokit/graphql-schema/blob/master/schema.graphql#L691 ). That's the first use of the at sign in the schema, I'd guess whatever `@deprecated` means in graphql is not yet supported in morpheus?

**Comment by nalchevanidze** [comment]
`@` symbol are for directives. #266 

i did not come up yet with idea how i could support directives.

but for now we can support directives only on parsing.( in your case you need it in client) so it should fix this issue.

 real implementation of directives as a API can be written in later version of `Morpheus`

**Comment by nalchevanidze** [comment]
https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Parsing/Internal/Terms.hs

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Parsing/Document/DataType.hs

for supporting  directives in parser

**Comment by shapr** [comment]
Since I'd like to use morpheus as a client, but don't know so much about graphql, could I remove all the directives from the schema and be able to talk to github's v4 API without problems?

**Comment by nalchevanidze** [comment]
yeah, it could be quick fix for you.
but support of directives in parser is necessary (as i see)

**Comment by nalchevanidze** [comment]
checkout actual master

https://github.com/morpheusgraphql/morpheus-graphql/commit/5d59bf1b60dfacdf630aff4281f9f1e258de5651

this should fix your problem

**Comment by nalchevanidze** [comment]
fixed and tested. in https://github.com/morpheusgraphql/morpheus-graphql/pull/282

**Comment by shapr** [comment]
Thanks, I'll try it out this weekend!
