### ISSUE TITLE
liftM is not working for mutations

### ISSUE THREAD

**Issue by tim2CF** [morpheusgraphql/morpheus-graphql#296]
Looks like atm it's not possible to perform IO in mutations. For queries works just fine.
```
    • No instance for (Monad (Resolver MUTATION IO ()))
        arising from a do statement
    • In a stmt of a 'do' block: ct <- liftM $ getCurrentTime
      In the expression:
        do ct <- liftM $ getCurrentTime
```

**Comment by nalchevanidze** [comment]
checkout this https://github.com/morpheusgraphql/morpheus-graphql/pull/298

**Comment by tim2CF** [comment]
cool, thanks 👍

**Comment by nalchevanidze** [comment]
i added some dummy examples how you could work with mutations, qurey and subscription, https://github.com/morpheusgraphql/morpheus-graphql/blob/9e644b261eef18b800de2d88f918e9ceeea06277/examples/src/Server/Sophisticated/API.hs#L143-L151

**Comment by nalchevanidze** [comment]
for breaking changes please read changelog,

**Comment by nalchevanidze** [comment]
Fixed
