### ISSUE TITLE
Documentation for the client code

### ISSUE THREAD

**Issue by bartavelle** [morpheusgraphql/morpheus-graphql#310]
Hello, I am not sure this should be an "issue", but I do not really know how to use the client part, even after reading the example.

I think I want to do something common : forward parts of the queries to backends. Is that something that I can do with relative ease? Could it be possible to have a code sample that shows how to query a remote GraphQL server in the module docs?

**Comment by sordina** [comment]
@bartavelle are there any particular types of examples that you're looking for?

**Comment by sordina** [comment]
I'm starting to add some here: https://github.com/morpheusgraphql/morpheus-graphql/pull/311

**Comment by bartavelle** [comment]
Sorry for the late answer! I am actually trying to write the code for : https://github.com/tsegismont/graphql-server-benchmark

I wrote the db part, but now I have to expose another graphql service in my schema.

**Comment by sordina** [comment]
@bartavelle ah interesting!

**Comment by nalchevanidze** [comment]
@bartavelle hi, did it helped ? or should we provide more examples?

**Comment by bartavelle** [comment]
I did not look at it yet, but I will probably have some time next year! I will let you know if I manage to write an entry for the benchmark, thanks a lot!

**Comment by nalchevanidze** [comment]
no updates for almost six months. so I think I can close it.
