### ISSUE TITLE
newbie confusion about query with parameters

### ISSUE THREAD

**Issue by shapr** [morpheusgraphql/morpheus-graphql#312]
I'm trying to get this part of the README to work:
```haskell
  fetchHero :: Args GetHero -> m (Either String GetHero)
  fetchHero = fetch jsonRes args
      where
        args = GetHeroArgs {getHeroArgsCharacter = Person {characterName = "Zeus"}}
        jsonRes :: ByteString -> m ByteString
        jsonRes = <GraphQL APi>
```
I think my primary problem is that I don't know what goes in place of "<GraphQL APi>"

I'm building a similar query against the GitHub API:
```haskell
defineByDocumentFile
  "schema.gql"
  [gql| query Next ($cursor:String)  { viewer { following(first: 100, after: $cursor) { pageInfo { hasNextPage endCursor } totalCount nodes { repository(name: "flmdata") { url } } } } } |]
```

I'm not clear on how to parrot the fetchHero above, this attempt did not work:
```haskell
fetchNext :: Args Next -> m (Either String Next)
fetchNext = fetch jsonRes args
    where args = GetNextArgs { getNextArgsAfter = String "foo"}
          jsonRes :: ByteString -> m ByteString
          jsonRes = _
```
Any advice or suggestions?
I'm happy to contribute docs once I understand how to do the things I need to do!

**Comment by nalchevanidze** [comment]
did you checkout #311

**Comment by nalchevanidze** [comment]
because there's been no answer for a long time. I'll close it.

 @shapr if there is remaining question we can discuss it in #310
