### ISSUE TITLE
Unable to use Floats in arguments in a graphql query

### ISSUE THREAD

**Issue by dnulnets** [morpheusgraphql/morpheus-graphql#325]
When using Floats as arguments in a query it will give an "Argument xxxxxx got invalid value ; Expected type "Float" found 1.", whenever the floats value is without decimals or only has decimals with zeros, e.g. 1, 1.0, 1.00000 and so on. With values that ends with a number other than zero it will work, e.g. 1.01, 1.2121 and so on.

This ones fail:

```
query FetchThemAll {
  queryItems (
    queryItemsSize : 1.00 )
  {
    itemName
  }
}
```

But works with 1.001 instead. Found in 0.7.1.

**Comment by nalchevanidze** [comment]
https://github.com/morpheusgraphql/morpheus-graphql/blob/fe193951fd5e357a1f3c17ad4b4919f7d61d1841/src/Data/Morpheus/Types/GQLScalar.hs#L66-L69

i found the problem, it only accepts float values, we should handle `Int` too

**Comment by dnulnets** [comment]
Did a quick test with parseValue (Int x) = pure $ fromIntegral x, and that did it. However it seems that it does not handle signed values for either Int or Float.

**Comment by nalchevanidze** [comment]
@dnulnets  fixed there: #327

**Comment by dnulnets** [comment]
Checked out the branch and it works fine! It does however accept -1.0 for Int:s but not -1.1, but I am not sure about graphQL coersion rules.

**Comment by nalchevanidze** [comment]
@dnulnets  i is not valid with GraphQL specification, but i think it is not major bug i think. is okey for now.
