### ISSUE TITLE
Communicate Error to User

### ISSUE THREAD

**Issue by cjduncana** [morpheusgraphql/morpheus-graphql#330]
I'm not clear on how I can communicate to the GraphQL user that their request failed. For example, if the user wants to create another user, but they use an email address already in the DB, I would like to communicate to the user that they tried to use an existing email address. How can I accomplish this? All the errors that my app has been thrown to the console instead.

**Comment by nalchevanidze** [comment]
how about `liftEither $ pure $ Left "message". i for next version will expose `failure`  for better handling errors.

**Comment by cjduncana** [comment]
This is what appears in the console when I used your suggestion:
`src/Data/Morpheus/Types/Internal/Resolving/Core.hs:142:12-53: Non-exhaustive patterns in record update`

**Comment by cjduncana** [comment]
I see that the examples in this repo only evaluates the `Right` branch. Is there an example that evaluates the `Left` branch?

**Comment by cjduncana** [comment]
I just pulled the example folder in this repo and tried changing a `Right` branch to a `Left` branch, and it works! I'll have to understand better the difference between these two code bases to solve this.

**Comment by cjduncana** [comment]
The only lead that I found is that [this line in the repo](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Types/Internal/Resolving/Core.hs#L147) could be considered as a problem since `state` could be in `Success` or `Failure`. If it's in the `Failure` state, then it wouldn't have an `events` to update. What I still can't figure out is how does my code trigger the error.

**Comment by nalchevanidze** [comment]
Yeap. I fixed it in new pull request. With default value

**Comment by nalchevanidze** [comment]
When i merge it will be fixed

**Comment by cjduncana** [comment]
Looking forward to that release.

**Comment by cjduncana** [comment]
Adding a link for reference sake: #328

**Comment by nalchevanidze** [comment]
you can use now `failRes`

**Comment by nalchevanidze** [comment]
@cjduncana Did it solved this problem for you?

**Comment by cjduncana** [comment]
I upgraded to 0.8 and used `liftEither` and worked like a charm. Thank you very much for your help and your hard work. I saw all the effort you've placed on this project over the weekend. Again, thank you very much! 🙌
