### ISSUE TITLE
Why arrows in generated code?

### ISSUE THREAD

**Issue by AnthonySuper** [morpheusgraphql/morpheus-graphql#334]
So, this is probably me missing something very obvious, but when you use `importGQLDocument` (or related functions), the quasiquoter generates code something like this:

```haskell

data Diety m = Deity {
    name :: (Arrow () (m Text)),
    power :: (Arrow () (m (Maybe Text)))
}
```

Looking around in the codebase a bit, I found that `Arrow` is defined as `(->)` in [this file](https://github.com/morpheusgraphql/morpheus-graphql/blob/7e117e6cde1c81eec3b982b37622a10abf48ce61/src/Data/Morpheus/Execution/Internal/Declare.hs). So that means that the fields have type `() -> (m Text)` or `() -> (m (Maybe Text))`. My understanding, however, was that `() -> a` is equivalent to simply `a` in Haskell due to laziness. So, why does the code generator make fields of type `() -> whatever` instead of just `whatever`?

I think I'm probably missing something obvious, but I figured I'd ask so other people who have the same question can figure it out (and maybe I'll open a PR to throw a line in the README about it or something for ease of finding, if you'd like).

**Comment by nalchevanidze** [comment]
Hi. Thank you for your issue. You are right. It is useless. For now it does not make sense anymore. The fields without arguments should be represented as 'm Type' and not as ' () -> mType'

**Comment by AnthonySuper** [comment]
Got it, cool. Do you have any plans on changing how the codegen works in the future? I'm currently trying to make a PR to get rid of the `() ->` bit, but it's proving quite a bit harder than I expected (mostly due to my unfamiliarity with template Haskell, I think).

**Comment by nalchevanidze** [comment]
oh. cool. there is a fix but works not fully. #335  .could you continue this PR?

**Comment by nalchevanidze** [comment]
or if you want implement it from start on your own. i can close my PR.

**Comment by AnthonySuper** [comment]
I'll see if I can help out with #335! It's way further along than what I've been tinkering with.

**Comment by nalchevanidze** [comment]
Okay.then .  I think I'm gonna finalize it. anyway It's almost done. You okay with it?

**Comment by AnthonySuper** [comment]
Sure. I apologize for not getting to it sooner, work and other things took up more of my time the last week than I expected.

**Comment by AnthonySuper** [comment]
Since this is now fixed, I'm closing this issue. Thank you very much, @nalchevanidze! This library is freaking awesome.

**Comment by nalchevanidze** [comment]
@AnthonySuper  thank you
