### ISSUE TITLE
Union types and interfaces

### ISSUE THREAD

**Issue by diskroma** [morpheusgraphql/morpheus-graphql#336]
Is support for union types and interfaces implemented already ?
If so, I cant figure out how to use them from your examples.

**Comment by nalchevanidze** [comment]
## interfaces

interfaces are supported on graphql `DSL`. 

https://github.com/morpheusgraphql/morpheus-graphql/blob/3034ac784e45bb5f50700ebdd54dbd501af8a94b/examples/assets/simple.gql#L13

but they are used only to validate concrete types . th does not generate types from them, becouse it would be pointless.

## unioins
 
unions in `DSL`:

https://github.com/morpheusgraphql/morpheus-graphql/blob/3034ac784e45bb5f50700ebdd54dbd501af8a94b/examples/src/Server/Sophisticated/api.gql#L79

unions with native Haskell types:

https://github.com/morpheusgraphql/morpheus-graphql#union-types
