### ISSUE TITLE
NonEmpty Instance of GQLType

### ISSUE THREAD

**Issue by cjduncana** [morpheusgraphql/morpheus-graphql#341]
NonEmpty is part of Haskell's basic libraries. How can I create a GQLType instance of NonEmpty?

**Comment by nalchevanidze** [comment]
if it is part of prelude then `morpheus` should provide `GQLType` instance  for it

**Comment by cjduncana** [comment]
Let me see if I can whip up a PR.

**Comment by nalchevanidze** [comment]
sounds good

**Comment by cjduncana** [comment]
How would I go about testing the guarantee provided by NonEmpty?

**Comment by nalchevanidze** [comment]
look at implementation of `Set`

https://github.com/morpheusgraphql/morpheus-graphql/blob/c66bde8e44eb79508eb6606acb6d621ec857b72f/src/Data/Morpheus/Execution/Server/Introspect.hs#L120-L124

https://github.com/morpheusgraphql/morpheus-graphql/blob/c66bde8e44eb79508eb6606acb6d621ec857b72f/src/Data/Morpheus/Execution/Server/Encode.hs#L104-L106

for inputs i think you can make it with same manner in:

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Execution/Server/Decode.hs

please add Decode instance for `Set` too

**Comment by nalchevanidze** [comment]
is addressed in #478
