### ISSUE TITLE
Splitting up type definitions and query/mutation definition

### ISSUE THREAD

**Issue by diskroma** [morpheusgraphql/morpheus-graphql#343]
I want to split my graphql type definitions into several files(User.gql and Lobby.gql) and also have several top level query and mutation definition files, since I want to have more than one endpoint (Endpoint1.gql, Endpoint2.gql...).
When i try to importDocumentWithNamespace with User.gql and Endpoint1.gql for example I get the following compile-time error:

* Expected kind `((* -> *) -> *) -> *',
    but `Resolver fieldOperationKind e m' has kind `* -> *'
* In the first argument of `Mutation', namely
    `(Resolver fieldOperationKind e m)'
  In the first argument of `morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.Encode', namely
    `(Mutation (Resolver fieldOperationKind e m))'
  In the instance declaration for
    `morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.ExploreResolvers morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (Mutation (Resolver fieldOperationKind e m)) o e m'

**Comment by nalchevanidze** [comment]
oh, which version do you use ? and can you provide more information?

**Comment by nalchevanidze** [comment]
please use `stack build --ghc-options -ddump-splices` and show me search there `Mutation` definition and encode instance  definition. should look like that.

```hs
 data Mutation m
  = Mutation {mutationCreateUser :: (m (User m)),
                mutationCreateAddress :: (m (Address m)),
                mutationSetAdress :: (m (Address m))}
  deriving Generic
```
and
```hs
instance (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ResolvingStrategy,
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind Resolver,
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither parentOparation morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ResolvingStrategy,
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.MapStrategy fieldOperationKind parentOparation,
examples        >               Typeable fieldOperationKind,
examples        >               Typeable parentOparation,
examples        >               Monad m,
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.Encode (Mutation (Resolver fieldOperationKind encodeEvent m)) parentOparation encodeEvent m,
examples        >               Typeable encodeEvent,
examples        >               Typeable m) =>
examples        >              morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.ExploreResolvers morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (Mutation (Resolver fieldOperationKind encodeEvent m)) parentOparation encodeEvent m where
examples        >       morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.exploreResolvers
examples        >         _
examples        >         (Mutation createUser createAddress setAdress)
examples        >         = morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ObjectRes
examples        >             [("createUser",
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.encode
examples        >                 createUser),
examples        >              ("createAddress",
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.encode
examples        >                 createAddress),
examples        >              ("setAdress",
examples        >               morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.encode
examples        >                 setAdress)]
```

**Comment by nalchevanidze** [comment]
i am using current master.

**Comment by diskroma** [comment]
I am using version 0.8.0.

I could reproduce the error in a minimal setting, since the compiler output got huge when i captured it from my original project.
So for the minimal setting i have one file "query.gql" which just provides one top-level query, that relies on the 'TestType', defined in the "types.gql" file.

In the haskell code I then call:
`importGQLDocumentWithNamespace "types.gql"`
 `importGQLDocumentWithNamespace "query.gql"`

The second import produces the error. The output of the stack build dump says:

test-project> build (lib + exe)
Preprocessing library for test-project-0.1.0.0..
Building library for test-project-0.1.0.0..
[2 of 2] Compiling Lib
/home/daniel/Documents/projects/haskell/test-project/src/Lib.hs:17:1-42: Splicing declarations
    importGQLDocumentWithNamespace "types.gql"
  ======>
    data TestType m
      = TestType {testTypeTest :: (morpheus-graphql-0.8.0:Data.Morpheus.Execution.Internal.Declare.Arrow () (m Text))}
      deriving GHC.Generics.Generic
    instance base-4.12.0.0:Data.Typeable.Internal.Typeable m =>
             morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.GQLType (TestType m) where
      type morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.CUSTOM (TestType m) = morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE
      type morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.KIND (TestType m) = Data.Morpheus.Kind.OUTPUT
      morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.__typeName _
        = pack
            (morpheus-graphql-0.8.0:Data.Morpheus.Execution.Document.GQLType.genTypeName
               "TestType")
      morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.description _
        = Nothing
    instance base-4.12.0.0:Data.Typeable.Internal.Typeable m =>
             morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.IntrospectRep morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (TestType m) where
      morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.introspectRep
        _proxy1
        _proxy2
        = (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.DataObject
             [(pack "test", 
               morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.DataField
                 {morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldName = pack
                                                                                             "test",
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldArgs = [],
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldArgsType = Nothing,
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldType = morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.TypeRef
                                                                                             {morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeConName = morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.__typeName
                                                                                                                                                                           (Data.Proxy.Proxy ::
                                                                                                                                                                              Data.Proxy.Proxy Text),
                                                                                              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeArgs = Nothing,
                                                                                              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeWrappers = []},
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldMeta = Just
                                                                                             ((morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.Meta
                                                                                                 Nothing)
                                                                                                [])})], 
           Prelude.concat
             [[morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.introspect
                 (Data.Proxy.Proxy :: Data.Proxy.Proxy Text)]])
    instance (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ResolvingStrategy,
              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver,
              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.MapStrategy fieldOperationKind o,
              base-4.12.0.0:Data.Typeable.Internal.Typeable fieldOperationKind,
              base-4.12.0.0:Data.Typeable.Internal.Typeable o,
              Monad m,
              morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.Encode (TestType (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)) o e m,
              base-4.12.0.0:Data.Typeable.Internal.Typeable e,
              base-4.12.0.0:Data.Typeable.Internal.Typeable m) =>
             morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.ExploreResolvers morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (TestType (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)) o e m where
      morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.exploreResolvers
        _
        (TestType test)
        = morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ObjectRes
            [("test", 
              morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.encode
                test)]
/home/daniel/Documents/projects/haskell/test-project/src/Lib.hs:19:1-42: Splicing declarations
    importGQLDocumentWithNamespace "query.gql"
  ======>
    data Query m
      = Query {queryGetTest :: (morpheus-graphql-0.8.0:Data.Morpheus.Execution.Internal.Declare.Arrow () (m TestType))}
      deriving GHC.Generics.Generic
    instance base-4.12.0.0:Data.Typeable.Internal.Typeable m =>
             morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.GQLType (Query m) where
      type morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.CUSTOM (Query m) = morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE
      type morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.KIND (Query m) = Data.Morpheus.Kind.OUTPUT
      morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.__typeName _
        = pack
            (morpheus-graphql-0.8.0:Data.Morpheus.Execution.Document.GQLType.genTypeName
               "Query")
      morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.description _
        = Nothing
    instance base-4.12.0.0:Data.Typeable.Internal.Typeable m =>
             morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.IntrospectRep morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (Query m) where
      morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.introspectRep
        _proxy1
        _proxy2
        = (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.DataObject
             [(pack "getTest", 
               morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.DataField
                 {morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldName = pack
                                                                                             "getTest",
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldArgs = [],
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldArgsType = Nothing,
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldType = morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.TypeRef
                                                                                             {morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeConName = morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.__typeName
                                                                                                                                                                           (Data.Proxy.Proxy ::
                                                                                                                                                                              Data.Proxy.Proxy TestType),
                                                                                              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeArgs = Nothing,
                                                                                              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Base.typeWrappers = []},
                  morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.fieldMeta = Just
                                                                                             ((morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.AST.Data.Meta
                                                                                                 Nothing)
                                                                                                [])})], 
           Prelude.concat
             [[morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Introspect.introspect
                 (Data.Proxy.Proxy :: Data.Proxy.Proxy TestType)]])
    instance (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ResolvingStrategy,
              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.LiftEither fieldOperationKind morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver,
              morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.MapStrategy fieldOperationKind o,
              base-4.12.0.0:Data.Typeable.Internal.Typeable fieldOperationKind,
              base-4.12.0.0:Data.Typeable.Internal.Typeable o,
              Monad m,
              morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.Encode (Query (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)) o e m,
              base-4.12.0.0:Data.Typeable.Internal.Typeable e,
              base-4.12.0.0:Data.Typeable.Internal.Typeable m) =>
             morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.ExploreResolvers morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (Query (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)) o e m where
      morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.exploreResolvers
        _
        (Query getTest)
        = morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.ObjectRes
            [("getTest", 
              morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.encode
                getTest)]

/home/daniel/Documents/projects/haskell/test-project/src/Lib.hs:19:1: error:
    • Expected kind ‘((* -> *) -> *) -> *’,
        but ‘morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m’ has kind ‘*
                                                                                                                               -> *’
    • In the first argument of ‘Query’, namely
        ‘(morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)’
      In the first argument of ‘morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.Encode’, namely
        ‘(Query (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m))’
      In the instance declaration for
        ‘morpheus-graphql-0.8.0:Data.Morpheus.Execution.Server.Encode.ExploreResolvers morpheus-graphql-0.8.0:Data.Morpheus.Types.GQLType.TRUE (Query (morpheus-graphql-0.8.0:Data.Morpheus.Types.Internal.Resolving.Resolver.Resolver fieldOperationKind e m)) o e m’
   |
19 | importGQLDocumentWithNamespace "query.gql"
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building package test-project-0.1.0.0 using:
      /home/daniel/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build lib:test-project exe:test-project-exe --ghc-options ""
    Process exited with code: ExitFailure 1

**Comment by nalchevanidze** [comment]
## problem
yea. it is problem caused by multiple SDL documents.  initial assumption was that all object types will be generated in one document. that why all external types are inferred as `SCALAR or ENUM` kinds that why they does not (receive `m` as argument in type generating)   


`importGQLDocumentWithNamespace "types.gql"` defines 

```hs
data TestType m = TestType {
  testTypeTest ::  () -> (m Text)
}
```

but `importGQLDocumentWithNamespace "query.gql"` defines 

```hs
data Query m = Query {
  queryGetTest ::  () -> m  TestType
}
```

instead of 

```hs
data Query m = Query {
  queryGetTest ::  () -> m  (TestType m)
}
```
that why encoding has trouble to handle it.

for now  multiple `**.gql` workes only if they are independent.

## solution

to fix it we must [reify](http://hackage.haskell.org/package/template-haskell-2.15.0.0/docs/Language-Haskell-TH.html#g:4) kind of `TestType` and if it is `Union || Object` and give proper signature `m (TestType m)` instead of  `m TestType`

it is not trivial, so may take time.  to fix it you could define `Query` and `Mutation` with native  
haskell types

**Comment by diskroma** [comment]
Okay, i see, thanks for the reply, ill try the option to define Query and Mutation with native haskell types tomorrow

**Comment by nalchevanidze** [comment]
@diskroma fixed there  #345. checkout actual master

**Comment by diskroma** [comment]
Worked like a charm, thanks for the quick reply again :)

**Comment by nalchevanidze** [comment]
fixed
