### ISSUE TITLE
Support Interfaces for Relay-compatible schemas

### ISSUE THREAD

**Issue by smatting** [morpheusgraphql/morpheus-graphql#344]
Is it currently possible to implement a Relay-compatible schema like this one:?

```graphql
interface Node {
  id: ID!
}

type Deity implements Node {
  id: ID!
  name: String!
  birthPlace: BirthPlace
}

type BirthPlace implements Node {
  id: ID!
  name: String
}

type Query {
  deity(name: String) : Deity
  node(id: ID!): Node
}
```

I don't know if it's possible to generate this schema from Haskell types, because of the necessary `interface Node` and `implements Node` parts.

Alternatively I could start with the schema and let morpheus generate the Haskell types from it.
But then I don't think I would have enough control over the TH generation process to generate for example `data Deity m = ...` instead of `data Deity = ..` to enable nested resolvers (le'ts assume `birthPlace` should be resolved lazily).

Can I somehow combine both approaches? I'm willing to use all kinds of workarounds.

**Comment by nalchevanidze** [comment]
hi @smatting , Haskell does not have  concept of interfaces. will be tricky to support it.

it is possible with TH. but not great one for public api.

**Comment by smatting** [comment]
Can I somehow work around it?  I really like to be able to use Relay as a frontend framework. I'm okay with giving up having the interfaces as Haskell types.

For example I could define `id: ID!` and `node()` without explictely mentioning interfaces. Then, to make relay happy, I'd could insert snippets like `" implements Node {"` and the interface definitions into the graphl schema. It's very hacky, but I guess it would work. Maybe there is a less hacky way?

**Comment by smatting** [comment]
Nevermind, I realized that doesn't make sense. Also to support `node(id: ID!): Node` you probably would need to represent `Node` internally as a union type over all types which implement the interface - sounds complicated.

**Comment by shinzui** [comment]
@nalchevanidze Is that something that you'll consider in the future? As GraphQL matures, Relay is proving to be the better option for production use cases. I've been using GraphQL for a few years now, and I'm going to use Relay on the client for my next project. I would have loved to use Haskell for the server.

**Comment by nalchevanidze** [comment]
it is little bit too tricky to simulate interfaces in the language that does not have one. only possible way i see with TemplateHaskell. 

```gql
interface Node {
  id: ID!
}

type Deity implements Node {
  id: ID!
  name: String!
  birthPlace: BirthPlace
}

type BirthPlace implements Node {
  id: ID!
  name: String
}

type Query {
  deity(name: String) : Deity
  node(id: ID!): Node
}
```

the current implementation reads and validates types but does not shows in introspection.
that means introspection would only see this:

```gql
type Deity {
  id: ID!
  name: String!
  birthPlace: BirthPlace
}

type BirthPlace  {
  id: ID!
  name: String
}

type Query {
  deity(name: String): Deity
  node(id: ID!): Node
}
```

**Comment by nalchevanidze** [comment]
it is some kind of possible to save interface information on `Deity , BirthPlace , Query` and show them on introspection.

**Comment by nalchevanidze** [comment]
but i am not quite sure if its good idea

**Comment by shinzui** [comment]
Hasura recently announced that they're working on supporting Relay. Their server is written in Haskell also, so it would be interesting to see how they solve the problem.

**Comment by russellmcc** [comment]
One idea I had for this that might feel relatively like native haskell from a library user's point of view is to use typeclasses and existential types for this, i.e., something like this:

```
data NodeSignature = NodeSignature {id :: ID} deriving (Generic, GQLType)

class Node a where
  sig :: a -> NodeSignature

data Query
  = Query
      { node :: ID -> (forall a. (Node a, GQLType a) => a)
      }
```

No idea at all how feasible this is to implement with generics, but to me existential types is the closest GHC has to an idea like GraphQL interfaces.

**Comment by russellmcc** [comment]
Also, could we re-open this issue?  Since returning interfaces is required to support a popular front-end framework, I think it would make sense for morpheus to eventually support this feature of GraphQL.

**Comment by nalchevanidze** [comment]
@russellmcc looks interesting. but not clear how it would work.

one possible solution can be template-haskell 

```hs
data Node = Node {
  id: ID!
} deriving (Generic a, GQLType a)

type Deity implements Node {
  id: ID!
  name: String!
} deriving (Generic a)

-- checks Deity and defines GQLType
$(implements 'Deity 'Node)

type Query {
  deity(name: String) : Deity
}
```

**Comment by russellmcc** [comment]
I'm not nearly comfortable enough with generics to see how this could be done without templates, so would gladly accept a solution that used templates!

I did poke around for similar ideas using Generics, and I found https://hackage.haskell.org/package/generic-lens-2.0.0.0/docs/Data-Generics-Product-Subtype.html which looks related.  This could use generics to at least infer that `Subtype Node Diety`, which seems like a start

**Comment by nalchevanidze** [comment]
@russellmcc  

as you see, i implemented first part for `interfaces` for `morpheus-graphql` core. 

still considering how we derive it  from haskell types in `morpheus-graphql` server.

**Comment by nalchevanidze** [comment]
i finally decided how to support interfaces see #445.

https://github.com/morpheusgraphql/morpheus-graphql/pull/445/files

it will still work with just regular types and generics (interface will be validated on runTime)

```hs
-- interface is just regular type derived with interface
newtype Person m = Person {name ::  m Text}
  deriving (Generic)

instance GQLType (Person m) where
  type KIND (Person m) = INTERFACE

-- in GQLType user can give, links between interface and objects
instance GQLType Deity where
  implements _ = [interface (Proxy @Person)]
```

for compile time validation just import schema from `DSL `
```gql
interface Account {
  name: String!
}

type User implements Account {
  name: String!
}
```

**Comment by shinzui** [comment]
Great work, @nalchevanidze.

**Comment by nalchevanidze** [comment]
i think now i can close it. will released in version 0.12.0

**Comment by russellmcc** [comment]
Sorry to comment back on so old an issue - I still think Relay-compatible schemas are not perfectly supported by Morpheus - relay depends on the following types of queries working:

with schema

```
interface Node {
  id: ID!,
}

type User implements Node {
  id: ID!,
  name: String!,
}

type Query {
  node(id: ID!): Node,
}
```

The query
```
{
  node(id: "4") {
    id
    ... on User {
      name
    }
  }
```

in other words, the `__typename` should return the "polymorphic" type for an interface rather than the interface type name.  If I'm understanding this correctly morpheus currently doesn't support it and just would return here with the typename equal to `Node` There's documentation for this approach [here](https://graphql.org/learn/global-object-identification/) on the graphql site and [here](https://relay.dev/docs/guides/graphql-server-specification/#object-identification) on the relay side.  So, sort of unfortunately supporting this is blocking using `relay` on the client side, which is a really nice library with lots of attractive features.

As others on this thread have said, it's not really that easy to imagine how to make this work in Haskell - maybe rather than generating a type for `Node` that just has an `id` morpheus could rather create `Node` as a variant of all implementors of `Node`?

**Comment by nalchevanidze** [comment]
@russellmcc i know the problem.  one possible solution is `type guards` described in the #596
