### ISSUE TITLE
Docs/ Add example of Custom Monad

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#346]

**Comment by dandoh** [comment]
I think I can work on this

**Comment by nalchevanidze** [comment]
thank you @dandoh

**Comment by nalchevanidze** [comment]
@cjduncana there is an example of custom monad https://github.com/morpheusgraphql/morpheus-graphql/tree/master/examples/src/Server/MonadIO

**Comment by nalchevanidze** [comment]
i think now we can close it
