### ISSUE TITLE
Export LiftEither so we can write resolvers for both QUERY and MUTATION

### ISSUE THREAD

**Issue by dandoh** [morpheusgraphql/morpheus-graphql#347]
Say we have this schema:
```graphql
type Query {
    person: Person!
}

type Mutation {
    createPerson(name: String!): Person!
}

type Person {
    name: String!
    address: String!
}
```

It seems like I need 2 version of person resolver for query and mutation (yes, I want top-level function signature), e.g:
```haskell
importGQLDocumentWithNamespace "graphql/schema.graphql"

data PersonData 
    = PersonData 
        Text -- name
        Text -- address

type Result a = IO (Either String a)

dbGetPerson :: Result PersonData
dbGetPerson = undefined

dbCreatePerson :: Text -> Result PersonData
dbCreatePerson name = undefined

rootResolver :: GQLRootResolver IO () Query Mutation Undefined
rootResolver =
    GQLRootResolver
        { queryResolver = Query {queryPerson} 
        , mutationResolver = Mutation {mutationCreatePerson}
        , subscriptionResolver = Undefined
        }
  where
    queryPerson :: () -> ResolveQ () IO Person
    queryPerson _ = do
        person <- liftEither dbGetPerson
        personResolverQ person

    mutationCreatePerson :: MutationCreatePersonArgs -> ResolveM () IO Person
    mutationCreatePerson MutationCreatePersonArgs
        { mutationCreatePersonArgsName = name
        } = do
        person <- liftEither $ dbCreatePerson name
        personResolverM person


-- | Repeat here
--
personResolverM :: PersonData -> ResolveM () IO Person
personResolverM (PersonData name address) = pure Person {personName, personAddress}
  where
    personName _ = pure name
    personAddress _ = pure address

personResolverQ :: PersonData -> ResolveQ () IO Person
personResolverQ (PersonData name address) = pure Person {personName, personAddress}
  where
    personName _ = pure name
    personAddress _ = pure address
```

If we export LiftEither, I imagine we can share person resolver like this: 
```haskell
type Leaf (o :: OperationType) a = Resolver o () a
type Graphql (o :: OperationType) a = Resolver o () (a (Resolver o () IO))

personResolver :: (LiftEither o Resolver) => Graphql o Person
personResolver (PersonData name address) = pure Person {personName, personAddress}
  where
    personName _ = pure name
    personAddress _ = pure address
```

**Comment by nalchevanidze** [comment]
hi @dandoh, i see the point. we should have some way to use `LiftEither` in constraints. but i think directly exposing `LiftEither` is not good idea for public api.(is internal class, has a confusing name that may change some day) . we can define more stabile constraint and export it for public api.

something like  this: https://github.com/morpheusgraphql/morpheus-graphql/blob/c2200813019c46de4485020310f042c1c7ca4ae6/src/Data/Morpheus/Execution/Server/Resolve.hs#L98

```hs
{-# LANGUAGE ConstraintKinds     #-}

-- TODO: maybe `WithOperation` or some better Name
type LiftOperation (o :: OperationType ) = (LiftEither o Resolver)
```

and then you could:

```hs
personResolver :: (LiftOperation o) => Graphql o Person
personResolver (PersonData name address) = pure Person {personName, personAddress}
  where
    personName _ = pure name
    personAddress _ = pure address
```

would be nice, if you could provide `PR` for it

**Comment by diskroma** [comment]
I would love to see this feature, since I have alot of code duplication due to this.
Sadly, I just started learning haskell, so I dont think im able to do solve this myself.

**Comment by dandoh** [comment]
> hi @dandoh, i see the point. we should have some way to use `LiftEither` in constraints. but i think directly exposing `LiftEither` is not good idea for public api.(it is internal class, has a confusing name that may change some day) . we can define more stabile constraint and expose it for public api.
> 
> something like this:
> 
> https://github.com/morpheusgraphql/morpheus-graphql/blob/c2200813019c46de4485020310f042c1c7ca4ae6/src/Data/Morpheus/Execution/Server/Resolve.hs#L98
> 
> ```haskell
> {-# LANGUAGE ConstraintKinds     #-}
> 
> -- TODO: maybe `WithOperation` or some better Name
> type LiftOperation (o :: OperationType ) = (LiftEither o Resolver)
> ```
> 
> and then you could:
> 
> ```haskell
> personResolver :: (LiftOperation o) => Graphql o Person
> personResolver (PersonData name address) = pure Person {personName, personAddress}
>   where
>     personName _ = pure name
>     personAddress _ = pure address
> ```
> 
> would be nice, if you could provide `PR` for it

Will do

**Comment by nalchevanidze** [comment]
so. i think we can close this issue. thanks @dandoh
