### ISSUE TITLE
Client schema definition

### ISSUE THREAD

**Issue by DrYSG** [morpheusgraphql/morpheus-graphql#385]
I am having issues with figuring out the correct *.graphql definitions to use for the following mutation and morph.

The server is a python/flask server. It implements:

```
mutation see_if_create_works {
  createTask(key: "stringA" , template: "stringB") {
    ok
    task {
      id_
      key
      template
    }
  }
}
```
and a query of the form:

```
query {
  allTasks {
    edges {
      node {
        id
        key
        template
        startTime
        status
      }
    }
  }
}
```
Here is how I am using defineByDocumentFile

```
defineByDocumentFile
  "schemas/crime.graphql"
  [gql|
    mutation createTask ($key: String!, $template: String!) {
        ok
        task {
          id_
          key
          template
        }
    }
    query allTasks {
      edges {
        node {
          id
          key
          template
          startTime
          status
        }
      }
    }
  |]
```

Invokation is done as:

```
createTask :: IO (Either String CreateTask)
createTask = fetch resolver args
  where
    args = GetCreateTaskArgs(key = "key1", template = "Template Test A")

allTasks :: IO (Either String AllTasks)
allTasks = fetch resolver ()
```

**Comment by nalchevanidze** [comment]
Morpheus parser parses only one operation per request  that means that you request query and mutation in different request.

**Comment by DrYSG** [comment]
@nalchevanidze 

Yes, I did try then as separate operations also before I wrote (and many other experiments) However, I do get that error when they are separate. (BTW: I do have the a stripped down version of the StarWars example working. So I might not be too far off, but something is still eluding me, and not clear from the examples and ReadMe

using one operation per request:

**Client.hs**

```
{-# LANGUAGE DeriveGeneric         #-}
{-# LANGUAGE DerivingStrategies    #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}

module CrimeClient
  ( fetchTasks
  , AllTasks(..)
  ) where

import           Data.ByteString.Lazy.Char8 (ByteString)
import           Data.Morpheus.Client       (Fetch (..), defineByDocumentFile,
                                             gql)
import           Data.Text                  (Text)

import           Network.HTTP.Req

defineByDocumentFile
  "schemas/crime.graphql"
  [gql|
    mutation createTask ($key: String!, $template: String!) {
        ok
        task {
          id_
          key
          template
        }
    }
  |]

defineByDocumentFile
  "schemas/crime.graphql"
  [gql|
  query allTasks {
    edges {
      node {
        id
        key
        template
        startTime
        status
      }
    }
  }
|]

resolver :: ByteString -> IO ByteString
resolver b =
  runReq defaultHttpConfig $ do
    let headers = header "Content-Type" "application/json"
    responseBody <$>
      req
        POST
        (https "localhost:7345/graphql")
        (ReqBodyLbs b)
        lbsResponse
        headers

createTask :: IO (Either String CreateTask)
createTask = fetch resolver args
  where
    args = GetCreateTaskArgs {key = "key1", template = "Template Test A"}

allTasks :: IO (Either String AllTasks)
allTasks = fetch resolver ()

```

schema:

**crime.graphql**

```
type Task {
  id: String!
  date_created: DateTime!
  template: Text!
  status: String!
  start_time: DateTime
}

type CreateTask {
  ok: Boolean
  task: Task
}

type Query {
  task: Task!
  allTasks: [Task]!
}

type Mutation {
  createTask (
    key: String
    template: String
  ): CreateTask
}

````
error using $key and $template in args of command

```
D:\CRIME\haskellGraphQLClient\src\CrimeClient.hs:21:1: error:
    [{"message":"Variable \"$key\" is never used in operation \"createTask\".","locations":[{"line":2,"column":26}]},{"message":"Variable \"$template\" is never used in operation \"createTask\".","locations":[{"line":2,"column":41}]}]
   |
21 | defineByDocumentFile
   | ^^^^^^^^^^^^^^^^^^^^^..
```

Error when I change the gql command to not use $key and $template in the args

```
D:\CRIME\haskellGraphQLClient\src\CrimeClient.hs:23:8: error:
    * [{"message":"offset=27:\nunexpected 'k'\nexpecting '#', ')', IgnoredTokens, empty Tuple value!, or white space\n","locations":[{"line":2,"column":26}]}]
    * In the quasi-quotation:
        [gql|
    mutation createTask (key: String!, template: String!) {
        ok
        task {
          id_
          key
          template
        }
    }
  |]
   |
23 |   [gql|
   |        ^...
Failed, no modules loaded.
```

**Comment by DrYSG** [comment]
Error returned when I comment out the mutation command and try just the query command (allTasks)

```
D:\CRIME\haskellGraphQLClient\src\CrimeClient.hs:34:1: error:
    [{"message":"Cannot query field \"edges\" on type \"Query\".","locations":[{"line":3,"column":11}]}]
   |
34 | defineByDocumentFile
   | ^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by nalchevanidze** [comment]
```[{"message":"Cannot query field \"edges\" on type \"Query\".","locations":[{"line":3,"column":11}]}]```

is error message of graphql, edge is not field of query. you should write this.

```hs
defineByDocumentFile
  "schemas/crime.graphql"
  [gql|
  query allTasks {
   allTasks {
    edges {
      node {
        id
        key
        template
        startTime
        status
        }
      }
    }
}
|]
```

**Comment by DrYSG** [comment]
Yes, I saw that. And also all I see in the python file that defines his schema is:

type Task {
  id: String!
  date_created: DateTime!
  template: Text!
  status: String!
  start_time: DateTime
}

So I am clueless where this edges (it is not in the source of the python server at all).
(I wish he was using Javascript and Apollo).

But failing that. Is there something I should be doing to the type Query  that would include the "edges"

```
type Query {
  task: Task!
  allTasks: [Task]!
}
```

Looking at the GraphiQL Docs, I am seeing the following:

(what a sad way to try to do Swagger and figure out the schema). Sorry to put you through this.

![image](https://user-images.githubusercontent.com/2865368/72561555-7ac1b400-3877-11ea-82ae-a2a95148e591.png)

![image](https://user-images.githubusercontent.com/2865368/72561721-caa07b00-3877-11ea-8f6d-9226e898568a.png)


![image](https://user-images.githubusercontent.com/2865368/72561643-a349ae00-3877-11ea-8168-93c95884ac29.png)

![image](https://user-images.githubusercontent.com/2865368/72561661-ad6bac80-3877-11ea-8101-db03f8aa5185.png)

**Comment by DrYSG** [comment]
I deciphered the bizarre tree that Python Flask GraphQL created. Thanks for the tips. I still have a problem with the mutation, but I will close this one, and make a more succinct description of the mutation with arguments issue.
