### ISSUE TITLE
how to use arguments in mutation

### ISSUE THREAD

**Issue by DrYSG** [morpheusgraphql/morpheus-graphql#386]
I am getting the error:

```
    [{"message":"Variable \"$key\" is never used in operation \"createTask\".","locations":[{"line":2,"column":26}]},{"message":"Variable \"$template\" is never used in operation \"createTask\".","locations":[{"line":2,"column":41}]}]
   |
24 | defineByDocumentFile
   | ^^^^^^^^^^^^^^^^^^^^^...

```
My schema looks like this:
( have tried using $key in the schema also, but that causes parse errors)

```
type Mutation {
  createTask (
    key: String
    template: String
  ): CreateTask
}

type CreateTask {
  ok: Boolean
  task: Task
}
```
I defined the query in the .hs file as:

```
defineByDocumentFile
  "schemas/crime.graphql"
  [gql|
    mutation createTask ($key: String!, $template: String!) {
        ok
        task {
          key
          template
        }
    }
  |]

makeTask :: IO (Either String createTask)
makeTask = fetch resolver args
  where
    args = GetCreateTaskArgs {key = "key1", template = "Template Test A"}
```

**Comment by nalchevanidze** [comment]
as i said ou are not using variables defined in your operation(mutation). 

if task has this arguments

```gql
 mutation CreateTask ($key: String!, $template: String!) {
        ok
        task ( key: $Key, template: $template) {
          key
          template
        }
    }
```
good practice would be to capitalize operations name.

if you are not familier with GraphQL may this tutorials help you.

https://graphql.org/learn/queries/#variables
https://graphqlmastery.com/blog/graphql-quick-tip-how-to-pass-variables-in-graphiql
https://www.tutorialspoint.com/graphql/graphql_mutation.htm
https://graphql.org/graphql-js/mutations-and-input-types/
https://blog.apollographql.com/react-graphql-tutorial-mutations-764d7ec23c15

**Comment by DrYSG** [comment]
I am familiar with JavaScript and Apollo. What I am not familiar with is how to do this in Morpheus and Haskell. I am unclear where the GetCreate is coming from and how to use.
