### ISSUE TITLE
Handling conflicting enum names

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#399]
Hi, I am using this library (which is great!) for talking to the github graphql api. They have the following enum definitions:

```graphql
"""
The possible states that can be requested when creating a check run.
You can only request certain states.
"""
enum RequestableCheckStatusState {
  COMPLETED
  # etc.
}

"""
The possible states for a check suite or run status.
"""
enum CheckStatusState {
  COMPLETED
  # etc
}
```

This causes problems using `defineByDocumentFile` as it generates multiple data constructors with the same name. `Multiple declarations of ‘COMPLETED’`. My query looks like:

```haskell
defineByDocumentFile
  "./resource/minimal-github.graphql"
  [gql|
    mutation CreateCheckRun ($checkRunInput: CreateCheckRunInput!) {
      createCheckRun(input: $checkRunInput) {
        checkRun {
          checkRunId: id
          name
          checkRunStatus: status
          repository {
            repositoryId: id
          }
          checkSuite {
            commit {
              oid
            }
          }
        }
      }
    }
  |]
```

Is there a way to avoid this conflict eg. by prefixing the data constructors?

**Comment by nalchevanidze** [comment]
oh. did not knew that. 

yeah. it is possible. we can prefix every enum 
`RequestableCheckStatusStateCOMPLETED`
and
`CheckStatusStateCOMPLETED`


https://github.com/morpheusgraphql/morpheus-graphql/blob/f76ac1d7ff40ce8d354b1dc83e3beaa1dde92548/src/Data/Morpheus/Execution/Client/Selection.hs#L247

it is not hard,  in this code 
```
tNamespace = [typeName]
```

will fix it, if you want you can make PR for it, or just wait and i will do when i have time for it.

**Comment by AlistairB** [comment]
Ok, I'll see if I can make a PR for it thanks :)

**Comment by AlistairB** [comment]
@nalchevanidze Unfortunately it seems the change I made was incomplete. It is now generating the prefixed data constructors in Haskell. However, when it translates these types back to graphql, it needs to unprefix the names.

Eg. I am now getting this error: `Variable $checkRunInput of type CreateCheckRunInput! was provided invalid value for status (Expected \\\"RequestableCheckStatusStateQUEUED\\\" to be one of: QUEUED, IN_PROGRESS, COMPLETED)`

I'm trying to understand how to do this in the code. Do you have any pointers?

**Comment by nalchevanidze** [comment]
to decode enum, we should update 

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Execution/Client/Aeson.hs#L124

to encode enum, we should update 

https://github.com/morpheusgraphql/morpheus-graphql/blob/61a2076b7cef66d197ad98001cf1fcd56e528fa5/src/Data/Morpheus/Execution/Client/Aeson.hs#L155

i will check it later

**Comment by AlistairB** [comment]
Ok thanks. I had a look and I will need to learn more template haskell to make the change.

I'm travelling for 4 days and (probably) won't have time to fix it. Will be able to focus on it after that.

Feel free to revert my previous PR for now as things are broken with it.

**Comment by AlistairB** [comment]
I think there are 2 options:

1. Generate the complete instance definitions, stripping / adding the typename from the data constructors for ToJSON / FromJSON.

2. Utilise aeson options to strip prefixes in the enum case. I think https://hackage.haskell.org/package/aeson-1.4.6.0/docs/Data-Aeson-Types.html#v:constructorTagModifier can do it.

2 means less template haskell + logic that needs to be in morpheus, however it also feels like more complexity with 2 layers of misdirection.

Unsure which I prefer. I might see what 2 looks like when written out for a single sum type.

**Comment by AlistairB** [comment]
Re 2 you can do something like:

```haskell
{-# LANGUAGE DeriveGeneric #-}
module AesonTest where

import Data.Aeson
import GHC.Generics (Generic)
import Data.List (stripPrefix)
import Data.Maybe (fromMaybe)

data RequestableCheckState =
    RequestableCheckStateQUEUED
  | RequestableCheckStateIN_PROGRESS
  | RequestableCheckStateCOMPLETED
  deriving (Generic, Show)

instance ToJSON RequestableCheckState where
  toEncoding = genericToEncoding (stripTypeNameOptions "RequestableCheckState")

stripTypeNameOptions :: String -> Options
stripTypeNameOptions typeNameToStrip = defaultOptions {
    constructorTagModifier = stripTypeName typeNameToStrip
  }

stripTypeName :: String -> String -> String
stripTypeName toStrip input = (fromMaybe input . stripPrefix toStrip) input
```

For the encoding case, however I can't find a similar simple way to do it with decoding. I think for now I am going to go down option 1 and try and template haskell generating the full manual instance definition.

**Comment by AlistairB** [comment]
Working on this today. Another interesting option is utilising https://hackage.haskell.org/package/aeson-1.4.6.0/docs/Data-Aeson-TH.html

**Comment by AlistairB** [comment]
I think the ideal if it were generated would be something along the lines of:

```haskell
data RequestableCheckState
  = RequestableCheckStateQUEUED
  | RequestableCheckStateIN_PROGRESS
  | RequestableCheckStateCOMPLETED
  deriving (Show)

instance ToJSON RequestableCheckState where
  toJSON a = case a of
    RequestableCheckStateQUEUED -> "QUEUED"
    RequestableCheckStateIN_PROGRESS -> "IN_PROGRESS"
    RequestableCheckStateCOMPLETED -> "COMPLETED"
  toEncoding a =
    text $
      case a of
        RequestableCheckStateQUEUED -> "QUEUED"
        RequestableCheckStateIN_PROGRESS -> "IN_PROGRESS"
        RequestableCheckStateCOMPLETED -> "COMPLETED"

instance FromJSON RequestableCheckState where
  parseJSON =
    withText "RequestableCheckState" $
      \case
        "QUEUED" -> pure RequestableCheckStateQUEUED
        "IN_PROGRESS" -> pure RequestableCheckStateIN_PROGRESS
        "COMPLETED" -> pure RequestableCheckStateCOMPLETED
        invalid -> fail $ "Unexpected RequestableCheckState: " <> unpack invalid
```

**Comment by AlistairB** [comment]
Actually option 1 does work fine for encoding + decoding

```haskell
instance ToJSON RequestableCheckState where
  toEncoding = genericToEncoding (stripTypeNameOptions "RequestableCheckState")

instance FromJSON RequestableCheckState where
  parseJSON = genericParseJSON (stripTypeNameOptions "RequestableCheckState")

stripTypeNameOptions :: String -> Options
stripTypeNameOptions typeNameToStrip =
  defaultOptions
    { constructorTagModifier = stripTypeName typeNameToStrip
    }

stripTypeName :: String -> String -> String
stripTypeName toStrip input = (fromMaybe input . stripPrefix toStrip) input
```

**Comment by AlistairB** [comment]
(Anyway.. clearly the currently solution is pure TH. Attempting to make the modifications)
