### ISSUE TITLE
Internal Error: Type Mismatch null

### ISSUE THREAD

**Issue by dataO1** [morpheusgraphql/morpheus-graphql#401]
When subscribing to a channel, like that 
```
resolveJoinedLobby :: Maybe User.SessionE
        -> Mongo.Pipe
        -> SubscriptionJoinedArgs
        -> ResolveS USEREVENT IO UserJoined
resolveJoinedLobby session pipe args = subscribe [USER] $ pure subResolver

    where
        subResolver (Event [USER] content) = lift (resolveJoinedLobby' content)
        resolveJoinedLobby' :: Content -> IO (Object QUERY USEREVENT UserJoined)
        resolveJoinedLobby' content = return UserJoined
                { username = return $ pack $ show $ contentID content
                }
```
i get the following error in the graphql-playground : 
```
{
  "errors": [
    {
      "message": "INTERNAL ERROR: Type mismatch null",
      "locations": []
    }
  ]
}
```
This also prints the following message in the console, where i started the process via stack:
```
"ApolloSubscription {apolloId = Nothing, apolloType = \"connection_init\", apolloPayload = Just (RequestPayload {payloadOperationName = Nothing, payloadQuery = Nothing, payloadVariables = Nothing})}"
```

As i said i use graphql-playground for the client and `morpheus-graphql-10.0.0`

**Comment by nalchevanidze** [comment]
@diskroma thanks, I'll check it out.

**Comment by nalchevanidze** [comment]
can you give me a request? there is some violated scalar argument. i think

**Comment by nalchevanidze** [comment]
it expected some scalar value but given null.

 the question is why request validation did not catch it. i would be glad, if you can provide schema for it.

**Comment by diskroma** [comment]
Sure, thanks for looking into this :)

The schema for the subscription looks like this:
```
-- Api.gql
type Subscription {
	joined(lobby: String!): UserJoined!
}
```
The type definition for UserJoined is in a seperated .gql file:
```
-- Types.gql
type UserJoined {
	username : String!
}
```

I import them seperately in the haskell file, where i handle the requests (the one from the original issue post):
```
import           LolHub.Graphql.Types -- which is just a wrapper for: importGQLDocument "src/LolHub/Graphql/Types.gql"
importGQLDocumentWithNamespace "src/LolHub/Graphql/Api.gql"
...
```
Maybe it has something to do with the fact, that they are defined in different documents. But for all other request types, this works as expected.

**Comment by diskroma** [comment]
Oh, and the request in playground looks like this:

```
subscription {
  joined(lobby: "5e388ff050a1be335b000002") {
    username
  }
}
```

**Comment by nalchevanidze** [comment]
@dataO1 hi please update to `0.14.0` and  try again.
