### ISSUE TITLE
Morpheus parser breaks when parsing `schema` definition

### ISSUE THREAD

**Issue by kutyel** [morpheusgraphql/morpheus-graphql#412]
I created a new GraphQL project using morpheus and when I added this to my `schema.gql`:

```graphql
schema {
  query: Query
  subscription: Subscription
}
```

The code generation broke with the following error:
```sh
    [{"message":"offset=292:\nunexpected \"schema {<newline>\"\nexpecting '#', TypeDefinition, end of input, or white space\n","locations":[{"line":24,"column":1}]}]
   |
19 | importGQLDocument "schema.graphql"
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Hasura had a similar problem with their parser, I'd be happy to contribute a fix if this is indeed something missing! 😉

**Comment by nalchevanidze** [comment]
yeah. sure.

 thanks :)

**Comment by kutyel** [comment]
How do you handle subscriptions if you cannot express them in the `schema.graphql`? 🤔

**Comment by nalchevanidze** [comment]
for now it lookups for type with Name Subscription.

issue is that parser cant handle parser can't  handle definition of schema.

```gql
schema {
```

if you remove it. it will take type query for `Query ` and type `Subscription`  for subscriptions.

**Comment by kutyel** [comment]
I see, thanks! 😄

**Comment by nalchevanidze** [comment]
@kutyel thanks again for your issue. do you wish wish contribute in this part or should i fix it?

**Comment by nalchevanidze** [comment]
as i see you already handled it in mu-haskell: https://github.com/higherkindness/mu-haskell/blob/master/graphql/src/Mu/GraphQL/Quasi/LostParser.hs

that why i ask you

**Comment by kutyel** [comment]
feel free to fix it if you have time, I've been very busy lately so sorry I couldn't find time to fix it myself!

**Comment by nalchevanidze** [comment]
hi @kutyel  after #476. you could be able to use `schema`. but that does not affect morpheus server. as long as it has a different scheme for deriving technique.

**Comment by kutyel** [comment]
Awesome, thanks! 🚀
