### ISSUE TITLE
Server seems to ignore union types when computing a Query

### ISSUE THREAD

**Issue by EdmundsEcho** [morpheusgraphql/morpheus-graphql#424]
A schema with a union
union is visible with introspection
union is visible when designing a query in graphiql

however,
when a query output depends on identifying the presence of the union, the query returns an error.
```gql
query viewObsETL {
  getObsEtl {
    subject {
      qualities {
        qualityValues {
          ...qualValues
        }
      }
    }
    measurements {
      components {
        componentValues {
          ...compValues
        }
      }
    }
  }
}
fragment qualValues on QualityValues {   # a union
  ... on TxtValues {  # object within the union
    txtValues
  }
  ... on IntValues {
    intValues
  }
}
fragment compValues on ComponentValues {   # a union
  ... on TxtValues {  # object within the union
    txtValues
  }
  ... on IntValues {
    intValues
  }
  ... on SpanValues {
    spanValues {
      rangeStart
    }
  }
} 
```
returns

```json
{
  "errors": [
    {
      "message": "Unknown type \"QualityValues\".",
      "locations": [
        {
          "line": 20,
          "column": 10
        }
      ]
    },
    {
      "message": "Unknown type \"ComponentValues\".",
      "locations": [
        {
          "line": 29,
          "column": 10
        }
      ]
    }
  ]
}
```

**Comment by nalchevanidze** [comment]
there is old version of validation. that why you don't get real error. 

the thing may is that you are using inputType in Fragment where you should use Output type.

please use actual master.  to check it

**Comment by nalchevanidze** [comment]
i did lots of validation refactoring there

**Comment by EdmundsEcho** [comment]
I don't think I'm defining the union as an input type.  Here is a snyppet of the schema:
```gql
"""
Quality values is a `union` of `TxtValues` and `IntValues`.
"""
union QualityValues
  = TxtValues
  | IntValues

```

**Comment by nalchevanidze** [comment]
@EdmundsEcho update to version `0.14.0` and use `debugInterpreter` instead of `Interpreter´it will print internal state of validation so we can check why it fails.

**Comment by nalchevanidze** [comment]
@EdmundsEcho hi if we want to fix this problem i need some more detai

**Comment by EdmundsEcho** [comment]
Great! I will send info later this week.

**Comment by nalchevanidze** [comment]
@EdmundsEcho i would recommend to update to the actual master since i made there some fixes that may solve your problem.

**Comment by EdmundsEcho** [comment]
Will do.  I was supposed to take a look this past weekend.  I will be sure to update you one way or another.  Thank you for the follow-up!  \- E

**Comment by nalchevanidze** [comment]
this ticket is quite outdated and close it until i am not sure what is here to solve. if there is same behaviour please reopen ticket with additional details

**Comment by EdmundsEcho** [comment]
Thank you.  I will when I have the chance.  The bug this issue describes may have been resolved in a later version.  I will be sure to circle back the moment I find confirmation one way or another.  The library is serving me well.  Again, thanks to your work here.
