### ISSUE TITLE
How to consider composing RootResolvers

### ISSUE THREAD

**Issue by EdmundsEcho** [morpheusgraphql/morpheus-graphql#425]
This is a feature request/inquiry  -- Is there a way to compose the root-resolvers?

**Comment by nalchevanidze** [comment]
please give me some example what do you mean.

**Comment by EdmundsEcho** [comment]
```haskell
rootResolverOne :: GQLRootResolver AppObs () Query Mutation Undefined
rootResolverOne =
    GQLRootResolver
        { queryResolver =
              Query
                  { qa = resolverQa
                  , qb = resolverQb
                  }
        , mutationResolver = Mutation {ma = resolverMa}
        , subscriptionResolver = Undefined
        }

rootResolverTwo :: GQLRootResolver AppObs () Query Mutation Undefined
rootResolverTwo =
    GQLRootResolver
        { queryResolver =
              Query
                  { qc = resolverQc
                  , gd = resolverGd
                  }
        , mutationResolver = Mutation {mb = resolverMb}
        , subscriptionResolver = Undefined
        }
```
The goal would be to compose the two definitions.  

The use case... 
Each module would have my resolvers, types and root resolver for the module.  Each module would only export the rootResolver.

I would have a separate module "Root" that would compose all of my Roots.

**Comment by nalchevanidze** [comment]
oooh. you mean merge this root types. it's possible but not yet implemented.

**Comment by EdmundsEcho** [comment]
Great!  Is there an outline of the syntax required? Perhaps I could move it along for you.  I ask for a started because I'm not yet up to speed on how to compose with type-level operations in the mix.

**Comment by nalchevanidze** [comment]
#425

no you can do it with:

```hs
api :: a -> m b
api = runApp (deriveApp rootResolverOne <> deriveApp rootResolverTwo)
```

**Comment by nalchevanidze** [comment]
@EdmundsEcho I think we can close it
