### ISSUE TITLE
Getting name clashes when input and type objects share fieldnames...

### ISSUE THREAD

**Issue by EdmundsEcho** [morpheusgraphql/morpheus-graphql#426]
Great library.  I'm making progress.  Near the end of the  this one phase, I encountered this error and can't seem to figure it out.  I had a similar one, and fixed it by changing the field names to avoid the name clash.  However, the use of the same field for the input and output types is clearly part of the spec, and what clearly works in the examples provided... So I'm surprised that I hit this error so far into the project.  Have you encountered this before?

Schema
```gql
input FieldValuesCompReqInput {
  txtValues: [String!]
  intValues: [Int!]
  reduced: Boolean!
}

type CompReqValues {
  values: ComponentValues
  reduced: Boolean!
}
```

compiling error
```haskell
.../src/Api/GQL/Request.hs:458:22: error:
    Ambiguous occurrence ‘reduced’
    It could refer to
       either the field ‘reduced’,
              imported from ‘Api.GQL.ObsETL’ at src/Api/GQL/Request.hs:45:51-64
           or the field ‘reduced’, defined at src/Api/GQL/Request.hs:75:1
           or the field ‘reduced’, defined at src/Api/GQL/Request.hs:75:1
    |
458 |       let reduced' = reduced $ componentValues req
    |                      ^^^^^^^

```
The hack of changing the field names works when I use `importGQLDocument`.

When I try to import using the namespace option, I loose the references to record fields. I'm not sure how to specify to include the constructors etc.

Thank you in advance for any pointers.

\- E

**Comment by nalchevanidze** [comment]
i think you should give it concrete type.so that compiler can decide which type to pick

**Comment by nalchevanidze** [comment]
sorry. as long i don't consider it as morpheus bug, i am going to close it.
