### ISSUE TITLE
Adjust server vs core package split?

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#456]
Hi,

Congrats on the 0.12.0 release. I like the package split between server and client. However, currently I am only using client functionality to talk to the github graphql api, but still need to include `morpheus-graphql` package.

Specifically, the github api has custom scalar definitions that I need to define. eg.

```graphql
"""
An ISO-8601 encoded date string. Unlike the DateTime type, GitTimestamp is not converted in UTC.
"""
scalar GitTimestamp
```

```haskell
import Data.Morpheus.Types (GQLScalar(..), GQLType(..), ScalarValue(..))
import Data.Morpheus.Kind (SCALAR)

newtype GitTimestamp = GitTimestamp {
    _gitTimestamp :: UTCTime
  }  deriving (Show, Generic)

instance GQLScalar GitTimestamp where
  parseValue (String x) = iso8601ParseM (unpack x) <&> GitTimestamp
  parseValue _          = Left "GitTimestamp must be a String"
  serialize (GitTimestamp value) = String (pack $ iso8601Show value)

instance GQLType GitTimestamp where
  type KIND GitTimestamp = SCALAR

instance A.ToJSON GitTimestamp where
  toJSON = A.toJSON . _gtGitTimestamp
  toEncoding = A.toEncoding . _gtGitTimestamp
```

Also I am using `ID` from `Data.Morpheus.Types` as github api also uses this, so I need it when building the query input.

Perhaps (parts of?) `Data.Morpheus.Types` and `Data.Morpheus.Kind` should be moved into the core package?

**Comment by nalchevanidze** [comment]
you don't need  `Data.Morpheus.Kind (SCALAR)` and  `GQLType(..)` in Morpheus Client.

` String "my Scalar value"` or `Int 3124134` are sufficient for it.

but i could implement it with  `GQLScalar`.  where `morpheus-client` does not replaces for Scalar types with `ScalarValue`, but user should provide `GQLScalar`. in that case `GQLScalar` can go to `core`and `client` packages too.

```hs
instance GQLScalar GitTimestamp where
  parseValue (String x) = iso8601ParseM (unpack x) <&> GitTimestamp
  parseValue _          = Left "GitTimestamp must be a String"
  serialize (GitTimestamp value) = String (pack $ iso8601Show value)
```

**Comment by nalchevanidze** [comment]
see #458 


now you need only 

```hs
import Data.Morpheus.Client
  ( GQLScalar (..),
    ScalarValue (..),
  )


newtype GitTimestamp = GitTimestamp {
    _gitTimestamp :: UTCTime
  }  deriving (Show, Generic)

instance GQLScalar GitTimestamp where
  parseValue (String x) = iso8601ParseM (unpack x) <&> GitTimestamp
  parseValue _          = Left "GitTimestamp must be a String"
  serialize (GitTimestamp value) = String (pack $ iso8601Show value)
```

from now `morpheus-graphql-client` must be sufficient.

**Comment by nalchevanidze** [comment]
you can import `ID` from `Data.Morpheus.Client (ID(..))`

**Comment by nalchevanidze** [comment]
Please close the issue if it meets your requirements.

**Comment by AlistairB** [comment]
Thanks @nalchevanidze ! I think this looks good. I've done some testing on my end.

I'm fine with just needing `morpheus-graphql-client`. I also think it is fine if you client users need to include `morpheus-graphql-core`, my main concern was with needing `morpheus-graphql`. Anyway, this works nicely thanks.
