### ISSUE TITLE
More control over field names when using "deriving GQLType"?

### ISSUE THREAD

**Issue by thomasjm** [morpheusgraphql/morpheus-graphql#505]
Thanks for this great library!

I was wondering if it could be possible to exert more control over the field names when you use `deriving GQLType`, in particular to make them better line up with `ToJSON`/`FromJSON` instances. For example, I like to make heavy use of Aeson's [fieldLabelModifier](https://hackage.haskell.org/package/aeson-1.5.3.0/docs/Data-Aeson.html#v:fieldLabelModifier) function to make data types like this:

```haskell
import qualified Data.Aeson as A
import Data.Morpheus.Types

data ProfileUserInfo = ProfileUserInfo {
  profileUserInfoUsername :: T.Text
  , profileUserInfoHashedEmail :: T.Text
  } deriving (Show, Generic, GQLType)
$(A.deriveJSON (A.defaultOptions { A.fieldLabelModifier = dropNAndToSnake (length "profileUserInfo") } )
               ''ProfileUserInfo)
```

This drops the initial string from the field and converts it to snake case, so the encoded JSON for `ProfileUserInfo "bob" "abcdef"` becomes `{"username": "bob", "hashed_email": "abcdef"}`. 

However, the Morpheus GraphQL representation of this still has field names like `profileUserInfoUsername` in it.

I was wondering if there might be some way to derive the `GQLType` instance to match, perhaps by passing in the Aeson [Options](https://hackage.haskell.org/package/aeson-1.5.3.0/docs/Data-Aeson.html#t:Options) object?

I saw some discussion about going in the other direction (from GraphQL schema to JSON instances) on #399, #402, but couldn't find anything on this.

**Comment by nalchevanidze** [comment]
it is only possible on Types generated By Template Haskell.  but i will add it to `GQLType` too.

**Comment by nalchevanidze** [comment]
implemented in: #513

use 

```hs
instance GQLType ProfileUserInfo where
  getNamespace _ = Just "ProfileUserInfo"
```

**Comment by nalchevanidze** [comment]
@thomasjm please close this. issue if it works for you

**Comment by thomasjm** [comment]
Thanks for all the progress on this!

I don't totally understand if this solves the problem. To make the derived `GQLType` instances match the `Aeson` instances perfectly, we need to be able to accomplish the same thing as the `Aeson` `fieldLabelModifier`. (And also other fields like the `constructorTagModifier`, and maybe even the `sumEncoding` although that might be harder.)

In the example I gave, notice how I transform the `profileUserInfoHashedEmail` field to snake case so it becomes `"hashed_email"`. Is this possible with the latest changes?

**Comment by nalchevanidze** [comment]
```hs
instance GQLType ProfileUserInfo where
  getNamespace _ = Just "ProfileUserInfo"
```
will stripNamespace: 

so that field `profileUserInfoHashedEmail` will be converted to `hashedEmail`.

now as i see. you need something like that.

```hs
instance GQLType ProfileUserInfo where
  valueLabelModifier  = dropNAndToSnake (length "profileUserInfo")
```

**Comment by thomasjm** [comment]
Exactly. It would probably be good to look at the different capabilities provided by the Aeson [Options](https://hackage.haskell.org/package/aeson-1.5.3.0/docs/Data-Aeson.html#t:Options) object.

FWIW I think getting this right would be pretty useful for encouraging adoption of Morpheus GraphQL. Most people who have existing REST APIs (like me) probably have their Aeson instances set up to encode a certain way, and it's much smoother to transition to Morpheus if we can get the same encodings from the GraphQL endpoint. That way we don't have to modify our frontends as much.

**Comment by nalchevanidze** [comment]
@thomasjm I don't think that using Aeson Options is not a good decision, because morpheus GraphQL may have other options in the future and we cannot extend it.

but i added:

```haskell
instance GQLType ProfileUserInfo where
  typeOptions _ = 
      GQLTypeOptions { 
        fieldLabelModifier = dropNAndToSnake (length "profileUserInfo") , 
        constructorTagModifier = id  
      }
```

**Comment by nalchevanidze** [comment]
@thomasjm please close this issue if it works for you

**Comment by thomasjm** [comment]
> morpheus GraphQL may have other options in the future and we cannot extend it

Hmm, not sure I understand this statement. Aeson has very flexible JSON encoding options so it's hard to imagine adding more to Morpheus that Aeson doesn't have (for JSON encoding at least). There's nothing stopping you from extending Morpheus with more options separately, i.e.

```haskell
instance GQLType ProfileUserInfo where
  aesonOptions = Just myAesonOptions
  otherOptions = Just myOtherOptions
```

I think to *fully* solve the problem would require something like what I suggested, so that Morpheus can express everything that Aeson can. To put it another way, Aeson's Options object currently has 8 fields: `fieldLabelModifier`, `constructorTagModifier`, `allNullaryToStringTag`, `omitNothingFields`, `sumEncoding`, `unwrapUnaryRecords`, `tagSingleConstructors`, `rejectUnknownFields`. Your recent change adds support for 2 of these. Finding a way to add support for all of them would be nice. (I'm not sure all of them make sense though--maybe some of the `sumEncoding` options don't make sense given the constraints of how GraphQL works?)

However, supporting `fieldLabelModifier` and `constructorTagModifier` is great! It already improves the situation for me, so thanks for that.

Maybe we should close this issue for now, and open new issues for adding other options if/when they're needed? I'll do that and you can reopen if you disagree.

(FWIW I have one suggestion for the API -- if you follow the design pattern where you don't expose the `GQLTypeOptions` constructor, but instead expose a `defaultGQLTypeOptions` and a set of accessors, then it's easier to extend in the future without breaking changes. See for example how the WAI [Request](https://hackage.haskell.org/package/wai-3.2.2.1/docs/Network-Wai.html#t:Request) works.)
