### ISSUE TITLE
Support JSON custom scalar values

### ISSUE THREAD

**Issue by thomasjm** [morpheusgraphql/morpheus-graphql#506]
It would be useful to be able to return arbitrary JSON values as scalars, without needing to serialize them to a string. I *think* this is a reasonable thing to do, based on the existence of this: https://github.com/taion/graphql-type-json.

It seems to be a simple change, I sketched it out here: https://github.com/thomasjm/morpheus-graphql/commit/6895f30c1344650e4ce30860cc86dc890601c513.

**Comment by nalchevanidze** [comment]
My intention is to make sure that my Morpheus Graphql meets the specifications and  Graphql client does not break when you using it.

if with your proposal it is still possible that i will accept it.  thomasjm@6895f30

**Comment by thomasjm** [comment]
Yes, I think it's totally fine with the specifications to do this.

I've been using my fork to send JSON values to a Javascript client and it works great.

**Comment by nalchevanidze** [comment]
@thomasjm  ok. then you can make PR. i will approve it

**Comment by nalchevanidze** [comment]
@thomasjm. so, should we close this issue?

**Comment by thomasjm** [comment]
Yep, thanks!
