### ISSUE TITLE
Capitalise scalar types generated by TH when they are lowercase

### ISSUE THREAD

**Issue by bubba** [morpheusgraphql/morpheus-graphql#519]
Some schemas generated by Hasura, for example, contain types that are all lower case:

```graphql
scalar uuid
```

When using `defineByDocumentFile`, the code generated by Template Haskell complains that the type constructor is illegal as it doesn't begin with a capital letter:

```
Main.hs:15:1: error:
    Illegal type constructor or class name: ‘uuid’
    When splicing a TH declaration:
      data LookupSpotifyOAuthArgs
    = LookupSpotifyOAuthArgs {id :: (GHC.Maybe.Maybe uuid)}
    deriving GHC.Generics.Generic
    deriving GHC.Show.Show
    deriving GHC.Classes.Eq
```

Would it be possible to automatically convert these references of `uuid` to `Uuid`?

**Comment by nalchevanidze** [comment]
@fixed in  #526. please close this issue if it works for you
