### ISSUE TITLE
Unknown Directive error for custom directives in query 

### ISSUE THREAD

**Issue by ashutoshrishi** [morpheusgraphql/morpheus-graphql#540]
We use our own graphql directive in the query which is interpreted by the graphql client before dispatching the query. It needs no server implementation for the directive. However, with `morpheus-graphql-0.14.0` and above, the query immediately fails on the server with: 

```
{
  "errors": [
    {
      "message": "Unknown Directive \"foo\".",
      "locations": [
        {
          "line": 1,
          "column": 60
        }
      ]
    }
  ]
}
```

`@foo` is the directive in the query. 

Is it possible to keep ignoring unrecognised directives or non-default graphql directives?

**Comment by nalchevanidze** [comment]
@ashutoshrishi  you can define Custom @foo on server.

if you define it with SDL

```gql
directive @foo on ...

type bla {
  field: @directive 
}
```

and import `importGQLDocument`

it will no more fail

**Comment by nalchevanidze** [comment]
i thinks question is already answered so i will close the issue
