### ISSUE TITLE
Query root type must be provided

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [morpheusgraphql/morpheus-graphql#546]
I have been trying to use the shopify GraphQL and have been having problems with morpheus-graphql-client understanding the shopify schema [shopify.json.zip](https://github.com/morpheusgraphql/morpheus-graphql/files/5372116/shopify.json.zip). I have received the compiler error:

```json
[{"message":"Query root type must be provided.","location":[]}]
```

from

```haskell
defineByIntrospectionFile
  "./shopify.json"
  [gql| {shop {name}} |]
```

**Comment by BebeSparkelSparkel** [comment]
Is there a quick fix to this? Or, should I just stick with bytestrings?

**Comment by nalchevanidze** [comment]
I am busy for a while (may I find time at the weekend), so the quickest fix would be using:

```hs
defineByDocumentFile  "./shopify.gql"  [gql| {shop {name}} |]
```

or if you want, you can make PR for an actual bug:

https://github.com/morpheusgraphql/morpheus-graphql/blob/e635ae3990c32d9a5ca4932baa079bb3fad04249/morpheus-graphql-client/src/Data/Morpheus/Client/JSONSchema/Parse.hs#L88

you should replace `fromElems ` with `buildSchema`

https://github.com/morpheusgraphql/morpheus-graphql/blob/e635ae3990c32d9a5ca4932baa079bb3fad04249/morpheus-graphql-core/src/Data/Morpheus/Types/Internal/AST/TypeSystem.hs#L376

**Comment by nalchevanidze** [comment]
fixed in #547

**Comment by BebeSparkelSparkel** [comment]
@nalchevanidze thanks I'll try it out today!

**Comment by nalchevanidze** [comment]
@BebeSparkelSparkel i assume that everything worked well and will close the issue

**Comment by BebeSparkelSparkel** [comment]
Just tried it out and it is now working with the shopify schema. Thanks for your help!
