### ISSUE TITLE
split GQLScalar for parsing and serializing

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [morpheusgraphql/morpheus-graphql#549]
It would be nice to have GQLScalar split into GQLParse and GQLSerialize so that parse and serialize do not both need to be implemented if not required. A lot of the times I am only parsing or serializing for a type and it is twice the work to define for both parsing and serializing.

**Comment by BebeSparkelSparkel** [comment]
similar to ToJSON and FromJSON

**Comment by nalchevanidze** [comment]
makes sense, will consider it

**Comment by BebeSparkelSparkel** [comment]
A little more context. I am only sending data one way and checking for error messages in the response
