### ISSUE TITLE
morpheus-graphql: support megaparsec 9

### ISSUE THREAD

**Issue by juhp** [morpheusgraphql/morpheus-graphql#552]
Could you allow morpheus-graphql to support megaparsec 9 please?
This is currently blocking Stackage Nightly from updating to megaparsec-9: commercialhaskell/stackage#5632

**Comment by nalchevanidze** [comment]
hi @juhp. i already relaxed bounds in september. see morpheus-graphql-core 0.15.1 bounds are  `>= 7.0.0     && <  10.0.0`

**Comment by juhp** [comment]
Yes, thanks but morpheus-graphql.cabal still depends on megaparsec < 9

See https://hackage.haskell.org/package/morpheus-graphql-0.15.1

**Comment by nalchevanidze** [comment]
i released version 0.16.0

https://hackage.haskell.org/package/morpheus-graphql does not used megaparsec at all.

and 

https://hackage.haskell.org/package/morpheus-graphql-core has upper bound <10

**Comment by juhp** [comment]
Thank you
