### ISSUE TITLE
Specify GQLType __name?

### ISSUE THREAD

**Issue by jaredramirez** [morpheusgraphql/morpheus-graphql#558]
Hey, thanks for the great library!

Is it possible to specify the GQLType name? Looking through the source, it looks like it'd be possible if `Data.Morpheus.Server.Types.GQLType` exposed `mkTypeData` and `GQLType` exposed `__type`.

My use case is that I use a single ID type for all of my DB ids with a phantom type to ensure type safety:
```haskell
newtype Id phantom = Id UUID

-- specify all my instances once, rather then for every id type

data UserIdPhantom
type UserId = Id UserIdPhantom

data AccountIdPhantom
type AccountId = Id AccountIdPhantom
```

This works great, but moprheus generates GQL type names for this like `Id_UserIdPhantom` and `Id_AccountIdPhantom`. This is fine, but on the client it's a bit vebose to read and the client doesn't really care about the phantom stuff. I think the names are coming from from `Data.Morpheus.Server.Types.GQLType.deriveTypeData` and `Typeable`. It would be cool if I could override this with something like:
```haskell
instance GQLType UserId where
  type KIND UserId = SCALAR
  __type _ = mkTypeData "UserId"
```

**Comment by nalchevanidze** [comment]
`__type` is hidden because of some reasons (one of which is security). i think we could use for modifications like this `GQLTypeOptions`.

https://github.com/morpheusgraphql/morpheus-graphql/blob/b9ac58e32cb1d2f6669a0bff3bcbc37b1dd3b23e/src/Data/Morpheus/Server/Types/GQLType.hs#L88

you can add new field : `typeNameModifier :: String -> String`

```hs
data GQLTypeOptions = GQLTypeOptions
  { ...
    typeNameModifier :: String -> String
  }
```

**Comment by bradsherman** [comment]
Hi, I'd like to try and solve this issue.
