### ISSUE TITLE
[client] response errors sometimes not made available

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#577]
Hi,

When using the `updateCheckRun` mutation on github graphql api in one case I get the following response.

```json
{
    "errors": [
      {
        "locations": [
          {
            "line": 3,
            "column": 7
          }
        ],
        "path": [
          "updateCheckRun"
        ],
        "message": "Could not resolve to a node with the global id of 'MDg6Q2hlY2tSdW4xNzk2OTI3MjMx'.",
        "type": "NOT_FOUND"
      }
    ],
    "data": {
      "updateCheckRun": null
    }
  }
```

The relevant graphql for this is:

```graphql
type Mutation {
    updateCheckRun(input: UpdateCheckRunInput!): UpdateCheckRunPayload
}
```

As per this definition ` "updateCheckRun": null` is a perfectly valid response and will json decode correctly. As such, morpheus assumes that everything is fine, however there are in fact errors. I believe the reason `UpdateCheckRunPayload` is nullable is because in the error case it won't be returned.

So I guess the assumption that a successful decode of the response = no errors is incorrect. ie. https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-client/src/Data/Morpheus/Client/Fetch.hs#L63 perhaps this success case should also pattern match on an empty error list.

Or you might want 3 responses of, success, success with errors, parse failure.

I'd happy to attempt a PR if you know what the ideal solution is.

**Comment by nalchevanidze** [comment]
hi @AlistairB, thank you i would be happy if you open a PR.



 > So I guess the assumption that a successful decode of the response = no errors is incorrect. ie. https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-client/src/Data/Morpheus/Client/Fetch.hs#L63 perhaps this success case should also pattern match on an empty error list.

i think official interface should stay same. However, decode must check errors and fail if there are any (like you suggested).

```hs
  fetch :: (Monad m, FromJSON a) => (ByteString -> m ByteString) -> Args a -> m (Either String a)
```

> Or you might want 3 responses of, success, success with errors, parse failure.

For this case we could add an additional operation `fetchPartial` . however I am not necessarily convinced of this.

**Comment by AlistairB** [comment]
Please ignore for now David I know you are busy! I just spent some time trying to integrate my PR into my project and had some more thoughts which I wanted to record.

There are 3 cases with the github graphql API

1. Successful fetch with data
2. Missing result.

```
{
  "data": {
    "repository": null
  },
  "errors": [
    {
      "type": "NOT_FOUND",
      "path": [
        "repository"
      ],
      "locations": [
        {
          "line": 7,
          "column": 3
        }
      ],
      "message": "Could not resolve to a Repository with the name 'facebook/reacttt'."
    }
  ]
}
```

3. Exception / Bad Request

```
{
  "errors": [
    {
      "path": [
        "query",
        "repository",
        "namee"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "Repository",
        "fieldName": "namee"
      },
      "locations": [
        {
          "line": 8,
          "column": 4
        }
      ],
      "message": "Field 'namee' doesn't exist on type 'Repository'"
    }
  ]
}
```

I assume exception is similar but not sure how to reproduce. Actually, looking at https://graphql.org/learn/serving-over-http/#response it seems that in the exception case you may get the data field, so it could be more case 2.

----

I think in some ways the current functionality is nice for the not found case. The issue is there may be other errors as well when you get a `null` result. Additionally, in some cases not found is very normal and expected (fetch random repository), but in other cases (update the 'CheckRun' I created) it is very unexpected and exceptional.

I would suggest the following for `fetch`.

```haskell
fetch :: (Monad m, FromJSON a) => (ByteString -> m ByteString) -> Args a -> m (Either (NonEmpty GQLError) (a, [GQLError]))
```

As such in the 3 above cases you get (vaguely sketched):

1. Success - `Right (aWithJustInside, [])`
2. Not Found - `Right (aWithNothing, [GQLError not found])`
3. Error - Left (GQLError error :| [])

In the first 1 my code will sanity check there are no errors and happily use the `a`.

In the second case:

- if a not found error is normal, I will check the GQLError is `NOT_FOUND` and just ignore it.
- if a not found error is unexpected, I will log the GQLError and go into exception handling mode

In the third caes:

- similarly I will log the GQLError and go into exception handling mode.

---

I guess as part of this you would need to add `type` to `GQLError`, although this appears to be non-standard. There might be another way to expose it / the full error.

**Comment by nalchevanidze** [comment]
HI. i think that `Right` must be only for `Succesfull` cases. 
therefore the type mus be `Either ([GQLError],Maybe a) a`:

1. Success - Right a
2. Partial Result with Errors - Left ([some error], Just a)
3. Error - Left ([some error], Nothing)

what do you think?

**Comment by AlistairB** [comment]
@nalchevanidze Yeah I think it is ok. It's fairly unclear to me the right modelling, partly because I am not that familiar with graphql.

For example, the 404/Not Found result is usually not considered exceptional with restful apis, so it makes me think it should be a `Right`.

Anyway, I think your modelling is fine, but I would tweak it slightly.

1. looks good.
2. If `Left` always has at least one error, I would use `NonEmpty` ie. `Left (NonEmpty errors, Just a)`
3. Same here

There is also another case of parse failure, which I modelled with a sum type.

https://github.com/morpheusgraphql/morpheus-graphql/blob/b76085132f15eb096b453f384d1a16ad350fc6e9/morpheus-graphql-client/src/Data/Morpheus/Client/Internal/Types.hs#L49-L59
https://github.com/morpheusgraphql/morpheus-graphql/blob/b76085132f15eb096b453f384d1a16ad350fc6e9/morpheus-graphql-client/src/Data/Morpheus/Client/Fetch.hs#L62

is how I did it, which is slightly different in that you get a `Right` if the `a` is parsed. Happy to go with your style though.

**Comment by AlistairB** [comment]
@nalchevanidze so are you happy with the following?

```haskell
fetch :: (Monad m, FromJSON a) => (ByteString -> m ByteString) -> Args a -> m (Either (FetchError a) a)

 data FetchError a
   = FetchParseFailure String 
   | FetchProducedErrors (NonEmpty GQLError) (Maybe a)
   deriving (Eq, Show) 
```

**Comment by nalchevanidze** [comment]
@AlistairB  yes. let try it
