### ISSUE TITLE
[app] Method for custom validation step of graphql operation

### ISSUE THREAD

**Issue by charlescrain** [morpheusgraphql/morpheus-graphql#579]
I'd like to add some middleware to requests that could do some protection/analysis of the requests. 

Would be cool to hook in after the parsing of query. 

What about a ValidateQuery a typeclass that the has a `validateQuery :: Schema Valid -> Operation Valid -> Bool`
then the `validateReq` function could become:
```haskell
validateReq ::
  ( Monad m,
    ValidateSchema s,
    ValidateQuery q
  ) =>
  Schema s ->
  Config ->
  GQLRequest ->
  ResponseStream event m ResolverContext
validateReq inputSchema config request = cleanEvents $ ResultT $ pure $ do
  validSchema <- validateSchema True config inputSchema
  schema <- internalSchema <:> validSchema
  operation <- parseRequestWith config validSchema request
  when (not $ validateQuery schema operation) fail -- Replace with whatever failure mechanism is available
  ...
  ```
  
Appreciate any feedback or other suggestions on how to do this

**Comment by nalchevanidze** [comment]
Hi @charlescrain. sound great idea. 

we could use `Config` for it.
option A: datas type `Config` has field `{ validateQuery ::  GQLRequest -> Either String GQLRequest }` where you can insert your validation (or analysis) algorithm. 
option B: The analysis algorithm is hardcoded in `validateQuery ` and you specify in `Config` the threshold above which it should reject heavy queries.

**Comment by nalchevanidze** [comment]
@charlescrain do you want to check it out?
