### ISSUE TITLE
LTS version in the README for version 0.17.0 needs to change to stackage nightly

### ISSUE THREAD

**Issue by EdmundsEcho** [morpheusgraphql/morpheus-graphql#599]
FYI - I quickly copied what was presented in the README to update my version of morpheus.  Not having worked with haskell for a few months, it took me a bit to figure out that the posted LTS of 16.2 is for an earlier version of the package. I might suggest posting two versions in the README: 

1. the latest version supported *not* using a nightly (e.g., 0.16.0)
2. the latest version that requires nightly (e.g., 0.17.0)

Alternatively, pin the compilation version 0.17.0 of morpheus using an alternative LTS with the `extra-deps` in the `stack.yaml` set to the following:
```
- morpheus-graphql-app-0.17.0@sha256:7561a7b371673417c8d7e4200ce2e79f01b5a8557547efdf341136459132d9cc,5425
- morpheus-graphql-core-0.17.0@sha256:4192366e2c23594a435364cc42832f2949620b8b116a69b57e59fde7111b1a0d,12939
```

I get that this is Haskell 101, but likely useful nonetheless.

**Comment by nalchevanidze** [comment]
i think this issue is outdated
