### ISSUE TITLE
Combining Morpheus with Freer-Simple

### ISSUE THREAD

**Issue by tapegram** [morpheusgraphql/morpheus-graphql#637]
Hi all! Apologies if this is not the appropriate venue for this but I'm trying to combine [Freer-Simple](https://hackage.haskell.org/package/freer-simple) for algebraic effects with Morpheus and am running into some issues. I was hoping that either someone would know what I'm doing wrong with `interpreter` and `rootResolver` or would be able to confirm that this is not currently possible to do and I can stick to the IO based approach that is working already.

I have a function with this type
```haskell
getAll :: Member OrganizationRepo effs =>
  Eff effs (Either OrganizationError [Organization])
```
I am trying to bubble up the effects to the rootResolver
```haskell
rootResolver' :: Member OrganizationRepo effs => RootResolver (Eff effs) () Query Undefined Undefined
rootResolver' =
  RootResolver
    { queryResolver = Query {
      organizations = organizations
    },
      mutationResolver = Undefined ,
      subscriptionResolver = Undefined
    }
  where
    organizations = liftEither $ toResponses <$> getAllOrgs
```

However when I attempt to create the `api` like so
```haskell
api :: Member OrganizationRepo effs => ByteString -> Eff effs ByteString
api = interpreter rootResolver'
```

I get an error like this
```
Could not deduce (base-4.14.1.0:Data.Typeable.Internal.Typeable
                      effs)
    arising from a use of ‘interpreter’
  from the context: Member OrganizationRepo effs
    bound by the type signature for:
               api :: forall (effs :: [* -> *]).
                      Member OrganizationRepo effs =>
                      ByteString -> Eff effs ByteString
```

Is this something that Morpheus supports currently and I am doing it wrong? If not, it would be cool if Morpheus supported something like this in the future!

**Comment by nalchevanidze** [comment]
Hi @tapegram , did you tried this?

```hs
api :: (Member OrganizationRepo effs, Typeable effs) => ByteString -> Eff effs ByteString
```

**Comment by tapegram** [comment]
@nalchevanidze that worked perfectly, thank you! Now I've moved on to trying to bubble it up another level if possible. So trying to convert

```haskell
routes :: OrganizationDBRef -> Web.Scotty.ScottyM ()
routes db = do
  post "/graphql" $ raw =<< (liftIO . handlers . api =<< body)

  where
    handlers = persistentOrgRepoHandler db
```

to something like
```haskell
routes :: Member OrganizationRepo effs =>  Eff effs (Web.Scotty.ScottyM ())
routes db = do
  post "/graphql" $ raw =<< (liftIO . api =<< body)
```

I realize this is at the boundary of Scotty and Morpheus so maybe this isn't so relevant here. I will continue messing around and can submit some example code if/when I get it working if anyone is interested in adding it to the docs / examples. Until then, if anyone more familiar with Scotty / Morpheus types has a suggestion on how I should approach this, it would be appreciated.

**Comment by tapegram** [comment]
In case anyone else was interested this ended up working so we could hoist the effect handlers up to running the server
```haskell
-- HTTP.hs
routes
  :: ( ScottyError e
     , Typeable effs
     , Member OrganizationRepo effs
     , LastMember IO effs
     )
  => ScottyT e (Eff effs) ()
routes = do
  post "/graphql" $ do
    result <- body >>= lift . api
    raw result
```
and 
```haskell
-- Lib.hs
server :: Bool -> IO () -> IO ()
server showStart readyAction = do
    db <- organizationDBRef
    scottyOptsT  (Options showStartMessage settings) **(persistentOrgRepoHandler db) routes**
  where
    settings =
        setBeforeMainLoop readyAction $
            setPort 8080
            defaultSettings
    showStartMessage = if showStart then 1 else 
```

Thanks for the help earlier! Morpheus is working great for us!

**Comment by nalchevanidze** [comment]
@tapegram do you want write an example post on our website about it?
for peope who are interseted on it.  

see https://github.com/morpheusgraphql/morpheus-graphql/blob/master/docs/src/pages/examples.mdx

**Comment by tapegram** [comment]
@nalchevanidze I'd be happy to!

**Comment by tapegram** [comment]
@nalchevanidze I got distracted and made an example app instead of a post on the website. Since I already made it I posted a PR. https://github.com/morpheusgraphql/morpheus-graphql/pull/640. LMK if that seems worth keeping, otherwise I'm happy to close it and just to the post.

I can follow up with an actual example post on the website.
