### ISSUE TITLE
No documentation for Client API

### ISSUE THREAD

**Issue by majkrzak** [morpheusgraphql/morpheus-graphql#652]
`Data.Morpheus.Client (defineByDocumentFile)` and similar is missing the documentation.
As first argument is "obvious" that second is not. Examples are provided, but their meaning is not explained at all.

**Comment by nalchevanidze** [comment]
second argument is actually AST of GraphQL query, i will update the documentation

**Comment by majkrzak** [comment]
Thank you. IMO, couple of words what the functions are doing will be helpful, as it will make very easy to understand whole `Data.Morpheus.Client` functionality. At least for me, the hardest part was to figure out that basically nothing is generated out of the schema file, and that it is only used for a validation of the queries/mutations from the 2nd parameter.

**Comment by nalchevanidze** [comment]
@majkrzak thanks good hint :)

**Comment by nalchevanidze** [comment]
@majkrzak [Data.Morpheus.Client](https://hackage.haskell.org/package/morpheus-graphql-client-0.20.0/docs/Data-Morpheus-Client.html)

does it looks bettering for now? or missing something?

**Comment by majkrzak** [comment]
@nalchevanidze It looks more clear now, thx. If it is complete and enough I honestly can't say as I'm biased with the fact I more or less know now how it is supposed to be used.

**Comment by nalchevanidze** [comment]
thanks @majkrzak,

all right, I think I will close it for now and if new issue with the same topic come up, I will try to improve the documentation further.
