### ISSUE TITLE
Expose arbitrary error fields in client response

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#653]
Following on from https://github.com/morpheusgraphql/morpheus-graphql/issues/577 , it is still cumbersome to detect a `NOT_FOUND` error from the [github graphql API](https://docs.github.com/en/graphql/overview/explorer).

eg.

```graphql
query { 
  repository(owner:"not-exist", name: "not-exist") {
    id
  }
}
```

```json
{
  "data": {
    "repository": null
  },
  "errors": [
    {
      "type": "NOT_FOUND",
      "path": [
        "repository"
      ],
      "locations": [
        {
          "line": 7,
          "column": 3
        }
      ],
      "message": "Could not resolve to a Repository with the name 'not-exist/not-exist'."
    }
  ]
}
```

which morpheus client represents as

```haskell
Left
        ( FetchErrorProducedErrors
            ( GQLError
                { message = "Could not resolve to a Repository with the name 'not-exist/not-exist'."
                , locations = Just
                    [ Position
                        { line = 3
                        , column = 7
                        }
                    ]
                , path = Just [ "repository" ]
                , errorType = Nothing
                , extensions = Nothing
                } :| []
            )
            ( Just
                ( FetchRepository { repository = Nothing } )
            )
        )
```

The way 0.17 worked and what you could do is ignore the error and if `a` parses and you get `data: { "repository": null }` exactly, then take that as a `NOT_FOUND` type error. This is ok, but it is possible to get other errors that are not `NOT_FOUND` that you may want to respond to differently.

I think the right solution is to expose `"type": "NOT_FOUND"` in `GQLError` somehow. However, it seems that `type` is a non-standard field, so I think perhaps the right solution is to expose a `Map` with other fields? ie.

```haskell
data GQLError = GQLError
  { message :: Message,
    locations :: Maybe [Position],
    path :: Maybe [Text],
    errorType :: Maybe ErrorType,
    extensions :: Maybe (Map Text Value),
    otherFields :: Map Text Value
  }
```

FWIW I don't think `Maybe (Map a b)` makes sense, as a `Map` can be empty, so I don't think the `Maybe` is necessary.

Thoughts?

Happy to attempt a PR.

**Comment by nalchevanidze** [comment]
in this case i would just expose field `type`  where `ErrorType` would have one Additional constructor `Custom`

**Comment by AlistairB** [comment]
That would be an easy solution for me, although `type` is [not included in the graphql spec](https://spec.graphql.org/June2018/#example-90475). Anyway, I will sketch out a PR at some point using this approach thanks.
