### ISSUE TITLE
[QUESTION] How to throw multiple errors

### ISSUE THREAD

**Issue by vitalibarozzi** [morpheusgraphql/morpheus-graphql#656]
Hello. :)

Recently I've started working with Morpheus at work and we where wondering if there were any ways to throw multiple errors at once; currently, using throwError we can only do it for GQLError, not GQLErrors.

I was wondering what I've missed. Any help? :/

**Comment by nalchevanidze** [comment]
hi @vitalibarozzi, maybe it is not the perfect way, however this will work for Morpheus.

```hs
throwErrors :: MonadError e m => [e] -> m b
throwErrors = traverse throwError
````

 monad `Result` will collect all errors (see implementation of Result monad)

```hs
instance Applicative (Result er) where
  pure x = Success x []
  Success f w1 <*> Success x w2 = Success (f x) (w1 <> w2)
  Failure e1 <*> Failure e2 = Failure (e1 <> e2)
  Failure (e :| es) <*> Success _ w = Failure (e :| es <> w)
  Success _ w <*> Failure (e :| es) = Failure (e :| es <> w)
```

you see:   `Failure e1 <*> Failure e2 = Failure (e1 <> e2)`

**Comment by vitalibarozzi** [comment]
Cool, @nalchevanidze, it seems working as we expect. Thanks for your help. :)
