### ISSUE TITLE
Support/ Scalar type ID

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#66]
[specifications](https://graphql.github.io/graphql-spec/June2018/#sec-ID)

- [x] always serialized as `String`
- [x] parsers only `String` and `int`
- [x] scalar type should be validated by instance function
- [x] update Changelog

**Comment by msvbg** [comment]
Why was this closed? IDs are still not in there.

**Comment by nalchevanidze** [comment]
fixed
