### ISSUE TITLE
[client] defineByDocumentFile' deprecated but no equivalent?

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#736]
`defineByDocumentFile' :: Q FilePath -> ExecutableSource -> Q [Dec]` takes a `Q FilePath` which is very useful as it enables using [makeRelativeToProject](https://hackage.haskell.org/package/file-embed-0.0.15.0/docs/Data-FileEmbed.html#v:makeRelativeToProject).

Using this function enables the paths to be correct when building from the command line and from within haskell language server.

However, the replacement function `declareLocalTypes` does not take a `Q FilePath`. Can a non-deprecated function be added to support this use case? Happy to make a PR if you advise how to solve it.

**Comment by nalchevanidze** [comment]
`declareLocalTypes` already uses [makeRelativeToProject](https://hackage.haskell.org/package/file-embed-0.0.15.0/docs/Data-FileEmbed.html#v:makeRelativeToProject) so there is not necessary `Q FilePath` anymore.
