### ISSUE TITLE
[client] Seems to no longer generate input types

### ISSUE THREAD

**Issue by AlistairB** [morpheusgraphql/morpheus-graphql#737]
Seems to no longer generate input types as of 0.20.0 (0.19.3 works). eg. I have this in my gql

```gql
input RerequestCheckSuiteInput {
  """
  The Node ID of the check suite.
  """
  checkSuiteId: ID!

  """
  The Node ID of the repository.
  """
  repositoryId: ID!
}
```

And I have:

```haskell
defineByDocumentFile'
  (makeRelativeToProject "../resource/minimal-github.graphql")
  [raw|
    mutation RerequestCheckSuite ($rerequestCheckSuiteInput: RerequestCheckSuiteInput!) {
      rerequestCheckSuite(input: $rerequestCheckSuiteInput) {
        checkSuite {
          checkRuns(first: 1) {
            edges {
              node {
                checkRunId: id
              }
            }
          }
        }
      }
    }
  |]
```

which fails with

```
    Not in scope: type constructor or class ‘RerequestCheckSuiteInput’
    Perhaps you meant one of these:
      ‘RerequestCheckSuite’ (line 18),
      ‘RerequestCheckSuiteArgs’ (line 18)
   |
18 | defineByDocumentFile'
   | ^
```

Using -ddump-splices I can confirm there is no `RerequestCheckSuiteInput` being generated. I can try and spin up a minimal repro if that helps?

**Comment by nalchevanidze** [comment]
yeah. in new version we split local and global types, which allows declaring multiple queries in same module and importing declared global types in multiple modules.  i tried not to modify the old functionalities, however probably it is the case. 

i would recommend to  use `declareGlobalTypes` for importing `RerequestCheckSuiteInput` and replace `defineByDocumentFile` with `declareLocalTypes`, since it is deprecated.

**Comment by AlistairB** [comment]
Ok fair enough. It does make it require a bit more boilerplate as I need to do things like:

```
declareGlobalTypesByName "../resource/minimal-github.graphql" ["CreateCheckRunInput", "RequestableCheckStatusState", "CheckStatusState"]

declareLocalTypesInline
  "../resource/minimal-github.graphql"
  [raw|
    mutation CreateCheckRun ($checkRunInput: CreateCheckRunInput!) {
      createCheckRun(input: $checkRunInput) {
```

to make sure all the types are available. Although I can see the benefit where you can generate types once and share them.

Ideally I would still prefer the old functionality, if that could kept that would be ideal. Still it works and I've managed to upgrade. Thanks!
