### ISSUE TITLE
New release incorporating #808?

### ISSUE THREAD

**Issue by thomasjm** [morpheusgraphql/morpheus-graphql#815]
I'd like to get the `morpheus-graphql` packages building on the newest Stackage nightly, which uses GHC 9.4. Any chance you could make a new release on Hackage which includes #808 ?

Thanks as always for the awesome library.

**Comment by vst** [comment]
> Thanks as always for the awesome library.

Likewise.

It would be nice to have a new release, because of #812, as well.

**Comment by nalchevanidze** [comment]
#814 solves problem in cleaner way, and since it is merged i will prepare release for it

**Comment by nalchevanidze** [comment]
see #816

**Comment by nalchevanidze** [comment]
https://github.com/morpheusgraphql/morpheus-graphql/releases/tag/0.27.1
