### ISSUE TITLE
`text` upper bounds revisions for 0.24.* 

### ISSUE THREAD

**Issue by jberryman** [morpheusgraphql/morpheus-graphql#817]
Hi, would you mind bumping the version bounds for `text` for versions 0.24.3 of the morpheus packages? I believe this can be done directly from hackage without creating a new version

Tested with `text ==2.0.1` which enables compatibility with ghc 9.4

We're not able to upgrade to newer morpheus at the moment

**Comment by jberryman** [comment]
:pray:

**Comment by jberryman** [comment]
hey thanks for looking into this, but I think you misunderstood. we are interested in a revision or new release of 0.24.x . The newest versions don't have any issues with 9.4 but we can't upgrade to them

**Comment by nalchevanidze** [comment]
@jberryman probably because of this one https://github.com/commercialhaskell/stackage/issues/6938

**Comment by jberryman** [comment]
> we can't upgrade 

what I mean is we don't have resources to devote to the migration. sorry to be unclear

**Comment by nalchevanidze** [comment]
Oh. I got it now. Will try:) but can't guarantee since i don't know if you can publish lower versions in hackage
