### ISSUE TITLE
Extraneous WS Message after error

### ISSUE THREAD

**Issue by ropwareJB** [morpheusgraphql/morpheus-graphql#838]
After an error is sent to the client via a websocket subscription, there is a following websocket message that is truncated:

1. The error message to the client
![image](https://github.com/morpheusgraphql/morpheus-graphql/assets/1904543/f681a6d1-dc51-4466-bbc1-eac871b92bcc)

2. The following truncated WS message
![image](https://github.com/morpheusgraphql/morpheus-graphql/assets/1904543/f5db0670-5790-4ad4-97e5-00b92cfed5a5)

**Comment by nalchevanidze** [comment]
can you give me more information?

**Comment by nalchevanidze** [comment]
@ropwareJB sorry i am closing it. but if you provide more information we can reopen
