### ISSUE TITLE
https://morpheus-graphql-slack-invite.herokuapp.com/ is down

### ISSUE THREAD

**Issue by jmikedupont2** [morpheusgraphql/morpheus-graphql#847]
In the docs https://morpheus-graphql-slack-invite.herokuapp.com/ the invite link is down, can you please send me an invite jmikedupont2@gmail.com thanks

**Comment by jmikedupont2** [comment]
https://github.com/morpheusgraphql/morpheus-graphql/blob/144a98ad7fd5022bbd890de92564d9ad286b7c00/morpheus-graphql-server/README.md?plain=1#L9

**Comment by nalchevanidze** [comment]
i think you can use new link on readme. its public you don't need manual invitation from me
